/* MODIFICAR LAS CLASES  */
alter PROCEDURE CONSULTORIO_EXT_MANTENIMIENTO_RS_MONITOREO
@RS_ID BIGINT,
@MO_FECHA CHAR(10),
@MO_EDAD VARCHAR(10),
@MO_PESO VARCHAR(10),
@MO_TALLA VARCHAR(10),
@ID_CIE10 bigint,
@COD_USU CHAR(8),
@TIPO CHAR(1)
AS
IF @TIPO = 'I'
BEGIN
	INSERT INTO [dbo].[CONSULTORIO_EXT_RS_MONITOREO]
           ([RS_ID]
           ,[MO_FECHA]
           ,[MO_EDAD]
           ,[MO_PESO]
           ,[MO_TALLA]
           ,[ID_CIE10]
           ,[ESTADO]
           ,[COD_USU]
           ,[NOM_PC])
     VALUES
           (@RS_ID,
           @MO_FECHA,
           @MO_EDAD, 
           @MO_PESO, 
           @MO_TALLA, 
           @ID_CIE10, 
           'A', 
           @COD_USU,
           HOST_NAME())
END
IF @TIPO = 'U'
BEGIN
	UPDATE [dbo].[CONSULTORIO_EXT_RS_MONITOREO]
    SET [MO_FECHA] = @MO_FECHA, 
      [MO_EDAD] = @MO_EDAD,
      [MO_PESO] = @MO_PESO, 
      [MO_TALLA] = @MO_TALLA,
      [ID_CIE10] = @ID_CIE10
	WHERE RS_ID = @RS_ID
END
IF @TIPO = 'E'
BEGIN
	UPDATE [dbo].[CONSULTORIO_EXT_RS_MONITOREO]
    SET ESTADO = 'D'
	WHERE RS_ID = @RS_ID
END

alter PROCEDURE CONSULTORIO_EXT_MANTENIMIENTO_RS_SEGUIMIENTO_ANEMIA
@RS_ID BIGINT,
@SA_FECHA CHAR(10),
@SA_EDAD VARCHAR(10),
@SA_RES VARCHAR(50),
@ID_CIE10 bigint,
@COD_USU CHAR(8),
@TIPO CHAR(1)
AS
IF @TIPO = 'I'
BEGIN
	INSERT INTO [dbo].[CONSULTORIO_EXT_RS_SEGUIMIENTO_ANEMIA]
           ([RS_ID]
           ,[SA_FECHA]
           ,[SA_EDAD]
           ,[SA_RES]
           ,[ID_CIE10]
           ,[ESTADO]
           ,[COD_USU]
           ,[NOM_PC])
     VALUES
           (@RS_ID, 
           @SA_FECHA, 
           @SA_EDAD, 
           @SA_RES, 
           @ID_CIE10,
           'A', 
           @COD_USU, 
           HOST_NAME())
END
IF @TIPO = 'U'
BEGIN
	UPDATE [dbo].[CONSULTORIO_EXT_RS_SEGUIMIENTO_ANEMIA]
   SET [SA_FECHA] = @SA_FECHA, 
      [SA_EDAD] = @SA_EDAD, 
      [SA_RES] = @SA_RES, 
      [ID_CIE10] = @ID_CIE10
 WHERE RS_ID = @RS_ID
END
IF @TIPO = 'E'
BEGIN
	UPDATE [dbo].[CONSULTORIO_EXT_RS_SEGUIMIENTO_ANEMIA]
   SET ESTADO = 'D'
 WHERE RS_ID = @RS_ID
END

alter PROCEDURE CONSULTORIO_EXT_MANTENIMIENTO_RS_SEGUIMIENTO_DESARROLLO
@RS_ID BIGINT,
@SD_FECHA CHAR(10),
@SD_EDAD VARCHAR(10),
@SD_RES VARCHAR(50),
@ID_CIE10 bigint,
@COD_USU CHAR(8),
@TIPO CHAR(1)
AS
IF @TIPO = 'I'
BEGIN
	
INSERT INTO [dbo].[CONSULTORIO_EXT_RS_SEGUIMIENTO_DESARROLLO]
           ([RS_ID]
           ,[SD_FECHA]
           ,[SD_EDAD]
           ,[SD_RES]
           ,[ID_CIE10]
           ,[ESTADO]
           ,[COD_USU]
           ,[NOM_PC])
     VALUES
           (@RS_ID, 
           @SD_FECHA, 
           @SD_EDAD,
           @SD_RES, 
           @ID_CIE10, 
           'A', 
           @COD_USU, 
           HOST_NAME())
END
IF @TIPO = 'U'
BEGIN
	UPDATE [dbo].[CONSULTORIO_EXT_RS_SEGUIMIENTO_DESARROLLO]
   SET [SD_FECHA] = @SD_FECHA, 
      [SD_EDAD] = @SD_EDAD, 
      [SD_RES] = @SD_RES, 
      [ID_CIE10] = @ID_CIE10
 WHERE RS_ID = @RS_ID
END
IF @TIPO = 'E'
BEGIN
	UPDATE [dbo].[CONSULTORIO_EXT_RS_SEGUIMIENTO_DESARROLLO]
   SET ESTADO = 'D'
 WHERE RS_ID = @RS_ID
END

alter PROCEDURE CONSULTORIO_EXT_MANTENIMIENTO_RS_SEGUIMIENTO_PARASITOSIS
@RS_ID BIGINT,
@SP_FECHA CHAR(10),
@SP_EDAD VARCHAR(10),
@ID_CIE10 bigint,
@SP_RECOMENDACIONES VARCHAR(100),
@COD_USU CHAR(8),
@TIPO CHAR(1)
AS
IF @TIPO = 'I'
BEGIN
	INSERT INTO [dbo].[CONSULTORIO_EXT_RS_SEGUIMIENTO_PARASITOSIS]
           ([RS_ID]
           ,[SP_FECHA]
           ,[SP_EDAD]
           ,[ID_CIE10]
           ,[SP_RECOMENDACIONES]
           ,[ESTADO]
           ,[COD_USU]
           ,[NOM_PC])
     VALUES
           (@RS_ID,
           @SP_FECHA, 
           @SP_EDAD, 
           @ID_CIE10,
           @SP_RECOMENDACIONES, 
           'A',
           @COD_USU, 
           HOST_NAME())
END
IF @TIPO = 'U'
BEGIN
	UPDATE [dbo].[CONSULTORIO_EXT_RS_SEGUIMIENTO_PARASITOSIS]
   SET [SP_FECHA] = @SP_FECHA,
      [SP_EDAD] = @SP_EDAD, 
      [ID_CIE10] = @ID_CIE10,
      [SP_RECOMENDACIONES] = @SP_RECOMENDACIONES
 WHERE RS_ID = @RS_ID
END
IF @TIPO = 'E'
BEGIN
	UPDATE [dbo].[CONSULTORIO_EXT_RS_SEGUIMIENTO_PARASITOSIS]
   SET ESTADO = 'D'
 WHERE RS_ID = @RS_ID
END

alter PROCEDURE CONSULTORIO_EXT_MANTENIMIENTO_RS_SEGUIIENTO_IRA
@RS_ID BIGINT,
@SI_FECHA CHAR(10),
@SI_EDAD VARCHAR(10),
@SI_RES VARCHAR(100),
@ID_CIE10 bigint,
@COD_USU CHAR(8),
@TIPO CHAR(1)
AS
IF @TIPO = 'I'
BEGIN
	INSERT INTO [dbo].[CONSULTORIO_EXT_RS_SEGUIIENTO_IRA]
           ([RS_ID]
           ,[SI_FECHA]
           ,[SI_EDAD]
           ,[SI_RES]
           ,[ID_CIE10]
           ,[ESTADO]
           ,[COD_USU]
           ,[NOM_PC])
     VALUES
           (@RS_ID, 
           @SI_FECHA, 
           @SI_EDAD, 
           @SI_RES,
           @ID_CIE10,
           'A', 
           @COD_USU, 
           HOST_NAME())
END
IF @TIPO = 'U'
BEGIN
	UPDATE [dbo].[CONSULTORIO_EXT_RS_SEGUIIENTO_IRA]
   SET [SI_FECHA] = @SI_FECHA, 
      [SI_EDAD] = @SI_EDAD, 
      [SI_RES] = @SI_RES, 
      [ID_CIE10] = @ID_CIE10
 WHERE RS_ID = @RS_ID
END
IF @TIPO = 'E'
BEGIN
	UPDATE [dbo].[CONSULTORIO_EXT_RS_SEGUIIENTO_IRA]
   SET ESTADO = 'D'
 WHERE RS_ID = @RS_ID
END

select * from CONSULTORIO_EXT_RS_MONITOREO
EXEC CONSULTORIO_EXT_RS_MONITOREO_LISTAR 5
ALTER PROCEDURE CONSULTORIO_EXT_RS_MONITOREO_LISTAR
@RS_ID VARCHAR(100)
AS
SELECT CM.MO_ID,CM.MO_EDAD,CM.MO_PESO,CM.MO_TALLA,CM.ID_CIE10,CIE.COD_ENF
FROM CONSULTORIO_EXT_RS_MONITOREO CM, CIE10 CIE
WHERE CIE.ID_CIE10 = CM.ID_CIE10
AND CM.ESTADO = 'A'
AND CM.RS_ID = @RS_ID