

EXEC CUENTAS_POR_PAGAR_TOTAL_VENTAS_GRAVADAS '15171898',5
ALTER PROCEDURE CUENTAS_POR_PAGAR_TOTAL_VENTAS_GRAVADAS
@DNI VARCHAR(8),
@TIPO CHAR(1)
AS
IF @TIPO = '5'
BEGIN
(SELECT SUM(CAJA_DOCUMENTO_DETALLE.precio_detalle * CAJA_DOCUMENTO_DETALLE.cantidad_detalle) AS 'VENTAS GRAVADAS'
FROM            CAJA_DOCUMENTO_CABECERA INNER JOIN
                         CAJA_DOCUMENTO_DETALLE ON CAJA_DOCUMENTO_CABECERA.id_documento = CAJA_DOCUMENTO_DETALLE.id_documento INNER JOIN
                         CAJA_PRECIOS ON CAJA_DOCUMENTO_DETALLE.cod_precio = CAJA_PRECIOS.cod_precio INNER JOIN
                         CAJA_NOMENCLATURA_CAJA ON CAJA_PRECIOS.cod_nomen_caja = CAJA_NOMENCLATURA_CAJA.cod_nomen_caja INNER JOIN
						 ADMISION_HISTORIA_CLINICA ON CAJA_DOCUMENTO_CABECERA.id_hc = ADMISION_HISTORIA_CLINICA.id_hc INNER JOIN
						 CAJA_JERARQUIA_FORMA_PAGO ON CAJA_DOCUMENTO_CABECERA.cod_jerar_forma_pago = CAJA_JERARQUIA_FORMA_PAGO.cod_jerar_forma_pago
						 WHERE CAJA_DOCUMENTO_DETALLE.estado_facturacion = 'F' 
						 AND ADMISION_HISTORIA_CLINICA.dni like @DNI
						 AND CAJA_NOMENCLATURA_CAJA.cod_grupo_nomen_aten IN ('GN05')
						 GROUP BY ADMISION_HISTORIA_CLINICA.dni)
END
IF @TIPO = 'T'
BEGIN
(SELECT SUM(ROUND(CAST (((CAJA_DOCUMENTO_DETALLE.precio_detalle * CAJA_DOCUMENTO_DETALLE.cantidad_detalle)) AS decimal (6,2)),2))
			   AS 'VENTAS INAFECTAS'
FROM            CAJA_DOCUMENTO_CABECERA INNER JOIN
                         CAJA_DOCUMENTO_DETALLE ON CAJA_DOCUMENTO_CABECERA.id_documento = CAJA_DOCUMENTO_DETALLE.id_documento INNER JOIN
                         CAJA_PRECIOS ON CAJA_DOCUMENTO_DETALLE.cod_precio = CAJA_PRECIOS.cod_precio INNER JOIN
                         CAJA_NOMENCLATURA_CAJA ON CAJA_PRECIOS.cod_nomen_caja = CAJA_NOMENCLATURA_CAJA.cod_nomen_caja INNER JOIN
						 ADMISION_HISTORIA_CLINICA ON CAJA_DOCUMENTO_CABECERA.id_hc = ADMISION_HISTORIA_CLINICA.id_hc INNER JOIN
						 CAJA_JERARQUIA_FORMA_PAGO ON CAJA_DOCUMENTO_CABECERA.cod_jerar_forma_pago = CAJA_JERARQUIA_FORMA_PAGO.cod_jerar_forma_pago
						 WHERE CAJA_DOCUMENTO_DETALLE.estado_facturacion = 'F' 
						 AND ADMISION_HISTORIA_CLINICA.dni like @DNI
						 AND CAJA_NOMENCLATURA_CAJA.cod_grupo_nomen_aten NOT IN ('GN05')
						 GROUP BY ADMISION_HISTORIA_CLINICA.dni) 
END
IF @TIPO = 'S'
BEGIN
(SELECT SUM(ROUND(CAST (((CAJA_DOCUMENTO_DETALLE.precio_detalle * CAJA_DOCUMENTO_DETALLE.cantidad_detalle)) AS decimal (6,2)),2))
			   AS 'VENTAS INAFECTAS'
FROM            CAJA_DOCUMENTO_CABECERA INNER JOIN
                         CAJA_DOCUMENTO_DETALLE ON CAJA_DOCUMENTO_CABECERA.id_documento = CAJA_DOCUMENTO_DETALLE.id_documento INNER JOIN
                         CAJA_PRECIOS ON CAJA_DOCUMENTO_DETALLE.cod_precio = CAJA_PRECIOS.cod_precio INNER JOIN
                         CAJA_NOMENCLATURA_CAJA ON CAJA_PRECIOS.cod_nomen_caja = CAJA_NOMENCLATURA_CAJA.cod_nomen_caja INNER JOIN
						 ADMISION_HISTORIA_CLINICA ON CAJA_DOCUMENTO_CABECERA.id_hc = ADMISION_HISTORIA_CLINICA.id_hc INNER JOIN
						 CAJA_JERARQUIA_FORMA_PAGO ON CAJA_DOCUMENTO_CABECERA.cod_jerar_forma_pago = CAJA_JERARQUIA_FORMA_PAGO.cod_jerar_forma_pago
						 WHERE CAJA_DOCUMENTO_DETALLE.estado_facturacion = 'F' 
						 AND ADMISION_HISTORIA_CLINICA.dni like @DNI
						 GROUP BY ADMISION_HISTORIA_CLINICA.dni) 	
END