EXEC [CUENTAS_POR_PAGAR_VENTAS_BOLETA_ELECTRONICA] '','',''

ALTER PROCEDURE [dbo].[CUENTAS_POR_PAGAR_VENTAS_BOLETA_ELECTRONICA]
@HC  varchar(200),
@FECHAI VARCHAR(10),
@FECHAF VARCHAR(10)
AS
IF @HC != ''
BEGIN
	IF @FECHAI = '' OR @FECHAF = ''
	BEGIN
		SELECT        CAJA_TIPO_DOCUMENTO.tipo_documento,RTRIM(CAJA_DOCUMENTO_CABECERA.serie_documento)+'-'+CAJA_DOCUMENTO_CABECERA.num_documento, CAJA_JERARQUIA_FORMA_PAGO.nom_forma_pago, 
								 ADMISION_HISTORIA_CLINICA.dni, ADMISION_HISTORIA_CLINICA.cod_hc, ADMISION_HISTORIA_CLINICA.ape_pat+ ' '+ 
								 ADMISION_HISTORIA_CLINICA.ape_mat+' '+ADMISION_HISTORIA_CLINICA.primer_nombre+' '+ ADMISION_HISTORIA_CLINICA.segundo_nombre, 
								 RTRIM(CAJA_MOTIVO_ANULACION_1.descripcion_anulacion), left(CAJA_DOCUMENTO_CABECERA.descuento,len(CAJA_DOCUMENTO_CABECERA.descuento)), left(CAJA_DOCUMENTO_CABECERA.sub_total_doc,len(CAJA_DOCUMENTO_CABECERA.sub_total_doc)), 
								 left(CAJA_DOCUMENTO_CABECERA.igv_doc,len(CAJA_DOCUMENTO_CABECERA.igv_doc)), left(CAJA_DOCUMENTO_CABECERA.total_doc,len(CAJA_DOCUMENTO_CABECERA.total_doc)), CAJA_DOCUMENTO_CABECERA.fecha_actu, 
								 CAJA_DOCUMENTO_CABECERA.hora_actu,CAJA_DOCUMENTO_CABECERA.Id_ActoMedico,CAJA_DOCUMENTO_CABECERA.id_documento
		FROM            CAJA_DOCUMENTO_CABECERA INNER JOIN
								 CAJA_MOTIVO_ANULACION ON CAJA_DOCUMENTO_CABECERA.cod_motiv_anu = CAJA_MOTIVO_ANULACION.cod_motiv_anu INNER JOIN
								 ADMISION_HISTORIA_CLINICA ON CAJA_DOCUMENTO_CABECERA.id_hc = ADMISION_HISTORIA_CLINICA.id_hc INNER JOIN
								 CAJA_MOTIVO_ANULACION AS CAJA_MOTIVO_ANULACION_1 ON 
								 CAJA_DOCUMENTO_CABECERA.cod_motiv_anu = CAJA_MOTIVO_ANULACION_1.cod_motiv_anu INNER JOIN
								 CAJA_TIPO_DOCUMENTO ON CAJA_DOCUMENTO_CABECERA.cod_tipo_documento = CAJA_TIPO_DOCUMENTO.cod_tipo_documento INNER JOIN
								 CAJA_JERARQUIA_FORMA_PAGO ON CAJA_DOCUMENTO_CABECERA.cod_jerar_forma_pago = CAJA_JERARQUIA_FORMA_PAGO.cod_jerar_forma_pago
								 WHERE 
						  
								 ADMISION_HISTORIA_CLINICA.DNI = @HC + '%' AND 
								 CAJA_DOCUMENTO_CABECERA.estado_pago='C' AND ESTADO_FACTURACION = 'A'
								 AND CAJA_DOCUMENTO_CABECERA.cod_motiv_anu = 'MA001' AND CAJA_DOCUMENTO_CABECERA.cod_jerar_forma_pago = 'P0001'
	END
	BEGIN
		SELECT        CAJA_TIPO_DOCUMENTO.tipo_documento,RTRIM(CAJA_DOCUMENTO_CABECERA.serie_documento)+'-'+CAJA_DOCUMENTO_CABECERA.num_documento, CAJA_JERARQUIA_FORMA_PAGO.nom_forma_pago, 
                         ADMISION_HISTORIA_CLINICA.dni, ADMISION_HISTORIA_CLINICA.cod_hc, ADMISION_HISTORIA_CLINICA.ape_pat+ ' '+ 
                         ADMISION_HISTORIA_CLINICA.ape_mat+' '+ADMISION_HISTORIA_CLINICA.primer_nombre+' '+ ADMISION_HISTORIA_CLINICA.segundo_nombre, 
                         RTRIM(CAJA_MOTIVO_ANULACION_1.descripcion_anulacion), left(CAJA_DOCUMENTO_CABECERA.descuento,len(CAJA_DOCUMENTO_CABECERA.descuento)), left(CAJA_DOCUMENTO_CABECERA.sub_total_doc,len(CAJA_DOCUMENTO_CABECERA.sub_total_doc)), 
                         left(CAJA_DOCUMENTO_CABECERA.igv_doc,len(CAJA_DOCUMENTO_CABECERA.igv_doc)), left(CAJA_DOCUMENTO_CABECERA.total_doc,len(CAJA_DOCUMENTO_CABECERA.total_doc)), CAJA_DOCUMENTO_CABECERA.fecha_actu, 
                         CAJA_DOCUMENTO_CABECERA.hora_actu,CAJA_DOCUMENTO_CABECERA.Id_ActoMedico,CAJA_DOCUMENTO_CABECERA.id_documento
FROM            CAJA_DOCUMENTO_CABECERA INNER JOIN
                         CAJA_MOTIVO_ANULACION ON CAJA_DOCUMENTO_CABECERA.cod_motiv_anu = CAJA_MOTIVO_ANULACION.cod_motiv_anu INNER JOIN
                         ADMISION_HISTORIA_CLINICA ON CAJA_DOCUMENTO_CABECERA.id_hc = ADMISION_HISTORIA_CLINICA.id_hc INNER JOIN
                         CAJA_MOTIVO_ANULACION AS CAJA_MOTIVO_ANULACION_1 ON 
                         CAJA_DOCUMENTO_CABECERA.cod_motiv_anu = CAJA_MOTIVO_ANULACION_1.cod_motiv_anu INNER JOIN
                         CAJA_TIPO_DOCUMENTO ON CAJA_DOCUMENTO_CABECERA.cod_tipo_documento = CAJA_TIPO_DOCUMENTO.cod_tipo_documento INNER JOIN
                         CAJA_JERARQUIA_FORMA_PAGO ON CAJA_DOCUMENTO_CABECERA.cod_jerar_forma_pago = CAJA_JERARQUIA_FORMA_PAGO.cod_jerar_forma_pago
						 WHERE 
						  
	                     ADMISION_HISTORIA_CLINICA.DNI = @HC + '%' AND 
						 CAJA_DOCUMENTO_CABECERA.estado_pago='C' AND ESTADO_FACTURACION = 'A'
						 AND CAJA_DOCUMENTO_CABECERA.cod_motiv_anu = 'MA001' AND CAJA_DOCUMENTO_CABECERA.cod_jerar_forma_pago = 'P0001'
						 AND CAJA_DOCUMENTO_CABECERA.fecha_actu BETWEEN @FECHAI AND @FECHAF
	END
END
ELSE
BEGIN
	IF @FECHAI = '' OR @FECHAF = ''
	BEGIN
		SELECT TOP 500 CAJA_TIPO_DOCUMENTO.tipo_documento,RTRIM(CAJA_DOCUMENTO_CABECERA.serie_documento)+'-'+CAJA_DOCUMENTO_CABECERA.num_documento, CAJA_JERARQUIA_FORMA_PAGO.nom_forma_pago, 
								 ADMISION_HISTORIA_CLINICA.dni, ADMISION_HISTORIA_CLINICA.cod_hc, ADMISION_HISTORIA_CLINICA.ape_pat+ ' '+ 
								 ADMISION_HISTORIA_CLINICA.ape_mat+' '+ADMISION_HISTORIA_CLINICA.primer_nombre+' '+ ADMISION_HISTORIA_CLINICA.segundo_nombre, 
								 RTRIM(CAJA_MOTIVO_ANULACION_1.descripcion_anulacion), left(CAJA_DOCUMENTO_CABECERA.descuento,len(CAJA_DOCUMENTO_CABECERA.descuento)), left(CAJA_DOCUMENTO_CABECERA.sub_total_doc,len(CAJA_DOCUMENTO_CABECERA.sub_total_doc)), 
								 left(CAJA_DOCUMENTO_CABECERA.igv_doc,len(CAJA_DOCUMENTO_CABECERA.igv_doc)), left(CAJA_DOCUMENTO_CABECERA.total_doc,len(CAJA_DOCUMENTO_CABECERA.total_doc)), CAJA_DOCUMENTO_CABECERA.fecha_actu, 
								 CAJA_DOCUMENTO_CABECERA.hora_actu,CAJA_DOCUMENTO_CABECERA.Id_ActoMedico,CAJA_DOCUMENTO_CABECERA.id_documento
		FROM            CAJA_DOCUMENTO_CABECERA INNER JOIN
								 CAJA_MOTIVO_ANULACION ON CAJA_DOCUMENTO_CABECERA.cod_motiv_anu = CAJA_MOTIVO_ANULACION.cod_motiv_anu INNER JOIN
								 ADMISION_HISTORIA_CLINICA ON CAJA_DOCUMENTO_CABECERA.id_hc = ADMISION_HISTORIA_CLINICA.id_hc INNER JOIN
								 CAJA_MOTIVO_ANULACION AS CAJA_MOTIVO_ANULACION_1 ON 
								 CAJA_DOCUMENTO_CABECERA.cod_motiv_anu = CAJA_MOTIVO_ANULACION_1.cod_motiv_anu INNER JOIN
								 CAJA_TIPO_DOCUMENTO ON CAJA_DOCUMENTO_CABECERA.cod_tipo_documento = CAJA_TIPO_DOCUMENTO.cod_tipo_documento INNER JOIN
								 CAJA_JERARQUIA_FORMA_PAGO ON CAJA_DOCUMENTO_CABECERA.cod_jerar_forma_pago = CAJA_JERARQUIA_FORMA_PAGO.cod_jerar_forma_pago
								 WHERE 
								 CAJA_DOCUMENTO_CABECERA.estado_pago='C' AND ESTADO_FACTURACION = 'A'
								 AND CAJA_DOCUMENTO_CABECERA.cod_motiv_anu = 'MA001' AND CAJA_DOCUMENTO_CABECERA.cod_jerar_forma_pago = 'P0001'
	END
	ELSE
	BEGIN
		SELECT        CAJA_TIPO_DOCUMENTO.tipo_documento,RTRIM(CAJA_DOCUMENTO_CABECERA.serie_documento)+'-'+CAJA_DOCUMENTO_CABECERA.num_documento, CAJA_JERARQUIA_FORMA_PAGO.nom_forma_pago, 
                         ADMISION_HISTORIA_CLINICA.dni, ADMISION_HISTORIA_CLINICA.cod_hc, ADMISION_HISTORIA_CLINICA.ape_pat+ ' '+ 
                         ADMISION_HISTORIA_CLINICA.ape_mat+' '+ADMISION_HISTORIA_CLINICA.primer_nombre+' '+ ADMISION_HISTORIA_CLINICA.segundo_nombre, 
                         RTRIM(CAJA_MOTIVO_ANULACION_1.descripcion_anulacion), left(CAJA_DOCUMENTO_CABECERA.descuento,len(CAJA_DOCUMENTO_CABECERA.descuento)), left(CAJA_DOCUMENTO_CABECERA.sub_total_doc,len(CAJA_DOCUMENTO_CABECERA.sub_total_doc)), 
                         left(CAJA_DOCUMENTO_CABECERA.igv_doc,len(CAJA_DOCUMENTO_CABECERA.igv_doc)), left(CAJA_DOCUMENTO_CABECERA.total_doc,len(CAJA_DOCUMENTO_CABECERA.total_doc)), CAJA_DOCUMENTO_CABECERA.fecha_actu, 
                         CAJA_DOCUMENTO_CABECERA.hora_actu,CAJA_DOCUMENTO_CABECERA.Id_ActoMedico,CAJA_DOCUMENTO_CABECERA.id_documento
FROM            CAJA_DOCUMENTO_CABECERA INNER JOIN
                         CAJA_MOTIVO_ANULACION ON CAJA_DOCUMENTO_CABECERA.cod_motiv_anu = CAJA_MOTIVO_ANULACION.cod_motiv_anu INNER JOIN
                         ADMISION_HISTORIA_CLINICA ON CAJA_DOCUMENTO_CABECERA.id_hc = ADMISION_HISTORIA_CLINICA.id_hc INNER JOIN
                         CAJA_MOTIVO_ANULACION AS CAJA_MOTIVO_ANULACION_1 ON 
                         CAJA_DOCUMENTO_CABECERA.cod_motiv_anu = CAJA_MOTIVO_ANULACION_1.cod_motiv_anu INNER JOIN
                         CAJA_TIPO_DOCUMENTO ON CAJA_DOCUMENTO_CABECERA.cod_tipo_documento = CAJA_TIPO_DOCUMENTO.cod_tipo_documento INNER JOIN
                         CAJA_JERARQUIA_FORMA_PAGO ON CAJA_DOCUMENTO_CABECERA.cod_jerar_forma_pago = CAJA_JERARQUIA_FORMA_PAGO.cod_jerar_forma_pago
						 WHERE 
						 CAJA_DOCUMENTO_CABECERA.estado_pago='C' AND ESTADO_FACTURACION = 'A'
						 AND CAJA_DOCUMENTO_CABECERA.cod_motiv_anu = 'MA001' AND CAJA_DOCUMENTO_CABECERA.cod_jerar_forma_pago = 'P0001'
						 AND CAJA_DOCUMENTO_CABECERA.fecha_actu BETWEEN @FECHAI AND @FECHAF
	END
END

EXEC [CUENTAS_POR_PAGAR_VENTAS_BOLETA_ELECTRONICA] '','',''

EXEC [CUENTAS_POR_PAGAR_VENTAS_CONSOLIDADO_DETALLES] '[CUENTAS_POR_PAGAR_VENTAS_CONSOLIDADO_DETALLES]',''
EXEC [CUENTAS_POR_PAGAR_VENTAS_CONSOLIDADO_DETALLES] 'CD000000000000001691',''
ALTER PROCEDURE [dbo].[CUENTAS_POR_PAGAR_VENTAS_CONSOLIDADO_DETALLES]
@DOCUMENTO VARCHAR(20),
@TIPO VARCHAR(2)
AS
IF @TIPO != ''
BEGIN
SELECT        CAJA_NOMENCLATURA_CAJA.nomen_caja,CAJA_NOMENCLATURA_CAJA.descripcion_nomen_tipo, left(CAJA_PRECIOS.precio,len(CAJA_PRECIOS.precio)), 
                         CAJA_DOCUMENTO_DETALLE.nom_consultorio_citas, CAJA_DOCUMENTO_DETALLE.cantidad_detalle, left(CAJA_DOCUMENTO_DETALLE.precio_detalle,len(CAJA_DOCUMENTO_DETALLE.precio_detalle)), 
                         left(CAJA_DOCUMENTO_DETALLE.descu_exo_detalle,len(CAJA_DOCUMENTO_DETALLE.descu_exo_detalle)),left(CAJA_DOCUMENTO_DETALLE.total_detalle,len(CAJA_DOCUMENTO_DETALLE.total_detalle)), CAJA_DOCUMENTO_DETALLE.personal_aten, 
                         CAJA_DOCUMENTO_DETALLE.num_aten, CAJA_DOCUMENTO_DETALLE.turno_cita, CAJA_DOCUMENTO_DETALLE.id_cod_doc_det
FROM            CAJA_DOCUMENTO_CABECERA INNER JOIN
                         CAJA_DOCUMENTO_DETALLE ON CAJA_DOCUMENTO_CABECERA.id_documento = CAJA_DOCUMENTO_DETALLE.id_documento INNER JOIN
                         CAJA_PRECIOS ON CAJA_DOCUMENTO_DETALLE.cod_precio = CAJA_PRECIOS.cod_precio INNER JOIN
                         CAJA_NOMENCLATURA_CAJA ON CAJA_PRECIOS.cod_nomen_caja = CAJA_NOMENCLATURA_CAJA.cod_nomen_caja
						 WHERE  CAJA_DOCUMENTO_CABECERA.id_documento like @DOCUMENTO AND
						  SUBSTRING(CAJA_NOMENCLATURA_CAJA.nomen_caja, 1, 2) = @TIPO
						  AND CAJA_DOCUMENTO_DETALLE.estado_facturacion = 'P'
						  END
IF @TIPO = ''
BEGIN
	SELECT        CAJA_NOMENCLATURA_CAJA.nomen_caja,CAJA_NOMENCLATURA_CAJA.descripcion_nomen_tipo, left(CAJA_PRECIOS.precio,len(CAJA_PRECIOS.precio)), 
                         CAJA_DOCUMENTO_DETALLE.nom_consultorio_citas, CAJA_DOCUMENTO_DETALLE.cantidad_detalle, left(CAJA_DOCUMENTO_DETALLE.precio_detalle,len(CAJA_DOCUMENTO_DETALLE.precio_detalle)), 
                         left(CAJA_DOCUMENTO_DETALLE.descu_exo_detalle,len(CAJA_DOCUMENTO_DETALLE.descu_exo_detalle)),left(CAJA_DOCUMENTO_DETALLE.total_detalle,len(CAJA_DOCUMENTO_DETALLE.total_detalle)), CAJA_DOCUMENTO_DETALLE.personal_aten, 
                         CAJA_DOCUMENTO_DETALLE.num_aten, CAJA_DOCUMENTO_DETALLE.turno_cita, CAJA_DOCUMENTO_DETALLE.id_cod_doc_det,CAJA_DOCUMENTO_DETALLE.estado_facturacion
FROM            CAJA_DOCUMENTO_CABECERA INNER JOIN
                         CAJA_DOCUMENTO_DETALLE ON CAJA_DOCUMENTO_CABECERA.id_documento = CAJA_DOCUMENTO_DETALLE.id_documento INNER JOIN
                         CAJA_PRECIOS ON CAJA_DOCUMENTO_DETALLE.cod_precio = CAJA_PRECIOS.cod_precio INNER JOIN
                         CAJA_NOMENCLATURA_CAJA ON CAJA_PRECIOS.cod_nomen_caja = CAJA_NOMENCLATURA_CAJA.cod_nomen_caja
						 WHERE  CAJA_DOCUMENTO_DETALLE.id_documento = @DOCUMENTO AND
						 CAJA_DOCUMENTO_DETALLE.estado_facturacion = 'P' 
END


EXEC [CUENTAS_POR_PAGAR_VENTAS_BOLETA_ELECTRONICA] '','',''
						 SELECT * FROM CAJA_DOCUMENTO_DETALLE WHERE id_documento = 'CD000000000000001691'

						 UPDATE CAJA_DO