/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.LABORATORIO;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import modelos.LABORATORIO.LAB_Clasificacion_Examen;
import modelos.LABORATORIO.LAB_Toma_Muestra_Detalle;

/**
 *
 * @author PC-SISTEMA
 */
public class frm_SOLICITUD_INVESTIGACION_BACT extends javax.swing.JFrame {
DefaultTableModel m;
    /**
     * Creates new form frm_SOLICITUD_INVESTIGACION_BACT
     */
    public frm_SOLICITUD_INVESTIGACION_BACT() {
        initComponents();
         buscar_HC.getContentPane().setBackground(Color.white); 
        buscar_HC.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.white); 
       
        setLocationRelativeTo(null);//en el centro
        setResizable(false);//para que no funcione el boton maximizar
    }
  public void LAB_HC_cargar(){
    try {
             String titulos[]={"N°","Codigo","N° H.C.","Paciente","DNI","Telefono","Dirección","Fecha de Nac.","Edad","Sexo"
             ,"Distrito","Provincia","Departamento"};
            m=new DefaultTableModel(null,titulos);
            JTable p=new JTable(m);
            String fila[]=new String[13];

            LAB_Clasificacion_Examen obj=new LAB_Clasificacion_Examen();
        String consulta="exec sp_BuscarHC ?";
        
        PreparedStatement cmd = obj.getCn().prepareStatement(consulta);
            cmd.setString(1, "");
        ResultSet r=cmd.executeQuery();
        int c=1;
        while(r.next()){
            fila[0]=String.valueOf(c)+"º";
            fila[1]=r.getString(1);
            fila[2]=r.getString(2);
            fila[3]=r.getString(3);
            fila[4]=r.getString(4);
            fila[5]=r.getString(5);
            fila[6]=r.getString(6);
            fila[7]=r.getString(7);
            fila[8]=r.getString(8);
            fila[9]=r.getString(9);
            fila[10]=r.getString(10);
            fila[11]=r.getString(11);
                m.addRow(fila);
                c++;
            }
            tb_HC.setModel(m);
            TableRowSorter<TableModel> elQueOrdena=new TableRowSorter<TableModel>(m);
            tb_HC.setRowSorter(elQueOrdena);
            this.tb_HC.setModel(m);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(rootPane, "Error en la tabla");
    }
}
    public void LAB_HC_formato(){
    tb_HC.getColumnModel().getColumn(0).setPreferredWidth(40);
    tb_HC.getColumnModel().getColumn(2).setPreferredWidth(100);
    tb_HC.getColumnModel().getColumn(3).setPreferredWidth(230);
    tb_HC.getColumnModel().getColumn(4).setPreferredWidth(100);
    tb_HC.getColumnModel().getColumn(6).setPreferredWidth(150);
    tb_HC.getColumnModel().getColumn(7).setPreferredWidth(110);
    tb_HC.getColumnModel().getColumn(8).setPreferredWidth(100);
    tb_HC.getColumnModel().getColumn(9).setPreferredWidth(100);
    
            //Ocultar    
    tb_HC.getColumnModel().getColumn(1).setMinWidth(0);
    tb_HC.getColumnModel().getColumn(1).setMaxWidth(0);
    tb_HC.getColumnModel().getColumn(5).setMinWidth(0);
    tb_HC.getColumnModel().getColumn(5).setMaxWidth(0);
    tb_HC.getColumnModel().getColumn(10).setMinWidth(0);
    tb_HC.getColumnModel().getColumn(10).setMaxWidth(0);
    tb_HC.getColumnModel().getColumn(11).setMinWidth(0);
    tb_HC.getColumnModel().getColumn(11).setMaxWidth(0);
    tb_HC.getColumnModel().getColumn(12).setMinWidth(0);
    tb_HC.getColumnModel().getColumn(12).setMaxWidth(0);
    tb_HC.getSelectionModel().setSelectionInterval(0, 0);
            tb_HC.requestFocus();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buscar_HC = new javax.swing.JDialog();
        btnBuscar1 = new javax.swing.JButton();
        txtbuscarHC = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_HC = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false; //Disallow the editing of any cell
            }};
            jpanel3 = new javax.swing.JPanel();
            titulo8 = new javax.swing.JLabel();
            jLabel25 = new javax.swing.JLabel();
            txtAp2 = new javax.swing.JTextField();
            txtAp4 = new javax.swing.JTextField();
            txtAp5 = new javax.swing.JTextField();
            txtAp6 = new javax.swing.JTextField();
            txtAp7 = new javax.swing.JTextField();
            txtAp8 = new javax.swing.JTextField();
            txtAp9 = new javax.swing.JTextField();
            jpanel = new javax.swing.JPanel();
            titulo5 = new javax.swing.JLabel();
            lblUsu = new javax.swing.JLabel();
            jLabel1 = new javax.swing.JLabel();
            jLabel2 = new javax.swing.JLabel();
            jLabel3 = new javax.swing.JLabel();
            jLabel9 = new javax.swing.JLabel();
            jPanel9 = new javax.swing.JPanel();
            txtPaciente = new javax.swing.JTextField();
            btnBuscarHC = new javax.swing.JButton();
            jLabel10 = new javax.swing.JLabel();
            lblhc = new javax.swing.JLabel();
            jLabel12 = new javax.swing.JLabel();
            jLabel13 = new javax.swing.JLabel();
            lblDireccion = new javax.swing.JLabel();
            jLabel15 = new javax.swing.JLabel();
            lblProvincia = new javax.swing.JLabel();
            jLabel18 = new javax.swing.JLabel();
            jLabel19 = new javax.swing.JLabel();
            jLabel20 = new javax.swing.JLabel();
            lblDNI = new javax.swing.JLabel();
            jLabel22 = new javax.swing.JLabel();
            lblEdad = new javax.swing.JLabel();
            lblSexo = new javax.swing.JLabel();
            lblTelefono = new javax.swing.JLabel();
            jLabel27 = new javax.swing.JLabel();
            lblDistrito = new javax.swing.JLabel();
            jLabel4 = new javax.swing.JLabel();
            jLabel5 = new javax.swing.JLabel();
            lblCama = new javax.swing.JLabel();
            lblServicio = new javax.swing.JLabel();
            jLabel7 = new javax.swing.JLabel();
            lblCodHC = new javax.swing.JLabel();
            jPanel10 = new javax.swing.JPanel();
            txtReferencia = new javax.swing.JTextField();
            jLabel8 = new javax.swing.JLabel();
            jLabel11 = new javax.swing.JLabel();
            jLabel14 = new javax.swing.JLabel();
            jPanel4 = new javax.swing.JPanel();
            jLabel21 = new javax.swing.JLabel();
            jLabel23 = new javax.swing.JLabel();
            jPanel5 = new javax.swing.JPanel();
            jLabel24 = new javax.swing.JLabel();
            jLabel26 = new javax.swing.JLabel();
            jPanel6 = new javax.swing.JPanel();
            jLabel28 = new javax.swing.JLabel();
            jLabel29 = new javax.swing.JLabel();
            jPanel7 = new javax.swing.JPanel();
            jLabel30 = new javax.swing.JLabel();
            jLabel31 = new javax.swing.JLabel();
            jLabel16 = new javax.swing.JLabel();
            jPanel11 = new javax.swing.JPanel();
            txtReferencia1 = new javax.swing.JTextField();
            jLabel17 = new javax.swing.JLabel();
            jPanel8 = new javax.swing.JPanel();
            jLabel32 = new javax.swing.JLabel();
            jLabel33 = new javax.swing.JLabel();
            jPanel12 = new javax.swing.JPanel();
            jLabel34 = new javax.swing.JLabel();
            jLabel35 = new javax.swing.JLabel();
            jLabel36 = new javax.swing.JLabel();
            jLabel37 = new javax.swing.JLabel();
            jLabel38 = new javax.swing.JLabel();
            jLabel39 = new javax.swing.JLabel();
            jPanel13 = new javax.swing.JPanel();
            jLabel40 = new javax.swing.JLabel();
            jLabel41 = new javax.swing.JLabel();
            jPanel14 = new javax.swing.JPanel();
            jLabel42 = new javax.swing.JLabel();
            jLabel43 = new javax.swing.JLabel();
            jLabel44 = new javax.swing.JLabel();
            jLabel45 = new javax.swing.JLabel();
            txtAp10 = new javax.swing.JTextField();
            jPanel15 = new javax.swing.JPanel();
            txtReferencia2 = new javax.swing.JTextField();
            jLabel47 = new javax.swing.JLabel();
            txtAp11 = new javax.swing.JTextField();
            jLabel48 = new javax.swing.JLabel();
            txtAp12 = new javax.swing.JTextField();

            buscar_HC.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
            buscar_HC.setTitle("SISGESH.::.Clasificación Examen");
            buscar_HC.setAlwaysOnTop(true);
            buscar_HC.setMinimumSize(new java.awt.Dimension(876, 692));
            buscar_HC.setResizable(false);

            btnBuscar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/Búsqueda-25.png"))); // NOI18N
            btnBuscar1.setBorder(null);
            btnBuscar1.setContentAreaFilled(false);
            btnBuscar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            btnBuscar1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnBuscar1ActionPerformed(evt);
                }
            });

            txtbuscarHC.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
            txtbuscarHC.setForeground(new java.awt.Color(0, 51, 51));
            txtbuscarHC.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    txtbuscarHCActionPerformed(evt);
                }
            });
            txtbuscarHC.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    txtbuscarHCKeyPressed(evt);
                }
                public void keyTyped(java.awt.event.KeyEvent evt) {
                    txtbuscarHCKeyTyped(evt);
                }
            });

            tb_HC.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
                },
                new String [] {
                    "Title 1", "Title 2", "Title 3", "Title 4"
                }
            ));
            tb_HC.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
            tb_HC.setRowHeight(25);
            tb_HC.getTableHeader().setReorderingAllowed(false);
            tb_HC.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    tb_HCMouseClicked(evt);
                }
            });
            tb_HC.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    tb_HCKeyPressed(evt);
                }
            });
            jScrollPane1.setViewportView(tb_HC);

            jpanel3.setBackground(new java.awt.Color(2, 67, 115));

            titulo8.setBackground(new java.awt.Color(0, 102, 102));
            titulo8.setFont(new java.awt.Font("Segoe UI Semilight", 0, 36)); // NOI18N
            titulo8.setForeground(new java.awt.Color(255, 255, 255));
            titulo8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            titulo8.setText("Historia Clínica");
            titulo8.setToolTipText("");
            titulo8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

            javax.swing.GroupLayout jpanel3Layout = new javax.swing.GroupLayout(jpanel3);
            jpanel3.setLayout(jpanel3Layout);
            jpanel3Layout.setHorizontalGroup(
                jpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(titulo8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 876, Short.MAX_VALUE)
            );
            jpanel3Layout.setVerticalGroup(
                jpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(titulo8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );

            jLabel25.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
            jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel25.setText("Búsqueda por H.C / Paciente / DNI");

            javax.swing.GroupLayout buscar_HCLayout = new javax.swing.GroupLayout(buscar_HC.getContentPane());
            buscar_HC.getContentPane().setLayout(buscar_HCLayout);
            buscar_HCLayout.setHorizontalGroup(
                buscar_HCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(buscar_HCLayout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 833, Short.MAX_VALUE)
                    .addGap(19, 19, 19))
                .addGroup(buscar_HCLayout.createSequentialGroup()
                    .addGap(300, 300, 300)
                    .addGroup(buscar_HCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtbuscarHC, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(buscar_HCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            buscar_HCLayout.setVerticalGroup(
                buscar_HCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buscar_HCLayout.createSequentialGroup()
                    .addGap(58, 58, 58)
                    .addGroup(buscar_HCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtbuscarHC, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, 0)
                    .addComponent(jLabel25)
                    .addGap(5, 5, 5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(38, Short.MAX_VALUE))
                .addGroup(buscar_HCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buscar_HCLayout.createSequentialGroup()
                        .addComponent(jpanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 644, Short.MAX_VALUE)))
            );

            setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
            setBackground(new java.awt.Color(255, 255, 255));

            txtAp2.setEditable(false);
            txtAp2.setBackground(new java.awt.Color(255, 255, 255));
            txtAp2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
            txtAp2.setForeground(new java.awt.Color(102, 102, 102));
            txtAp2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            txtAp2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
            txtAp2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            txtAp2.setPreferredSize(new java.awt.Dimension(18, 18));
            txtAp2.setSelectionColor(new java.awt.Color(255, 51, 51));
            txtAp2.addCaretListener(new javax.swing.event.CaretListener() {
                public void caretUpdate(javax.swing.event.CaretEvent evt) {
                    txtAp2CaretUpdate(evt);
                }
            });
            txtAp2.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    txtAp2MouseClicked(evt);
                }
            });
            txtAp2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    txtAp2ActionPerformed(evt);
                }
            });

            txtAp4.setEditable(false);
            txtAp4.setBackground(new java.awt.Color(255, 255, 255));
            txtAp4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
            txtAp4.setForeground(new java.awt.Color(102, 102, 102));
            txtAp4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            txtAp4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
            txtAp4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            txtAp4.setPreferredSize(new java.awt.Dimension(18, 18));
            txtAp4.setSelectedTextColor(new java.awt.Color(102, 102, 102));
            txtAp4.setSelectionColor(new java.awt.Color(255, 204, 51));
            txtAp4.addCaretListener(new javax.swing.event.CaretListener() {
                public void caretUpdate(javax.swing.event.CaretEvent evt) {
                    txtAp4CaretUpdate(evt);
                }
            });
            txtAp4.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    txtAp4MouseClicked(evt);
                }
            });
            txtAp4.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    txtAp4ActionPerformed(evt);
                }
            });

            txtAp5.setEditable(false);
            txtAp5.setBackground(new java.awt.Color(255, 255, 255));
            txtAp5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
            txtAp5.setForeground(new java.awt.Color(102, 102, 102));
            txtAp5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            txtAp5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
            txtAp5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            txtAp5.setPreferredSize(new java.awt.Dimension(18, 18));
            txtAp5.setSelectedTextColor(new java.awt.Color(102, 102, 102));
            txtAp5.setSelectionColor(new java.awt.Color(255, 204, 51));
            txtAp5.addCaretListener(new javax.swing.event.CaretListener() {
                public void caretUpdate(javax.swing.event.CaretEvent evt) {
                    txtAp5CaretUpdate(evt);
                }
            });
            txtAp5.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    txtAp5MouseClicked(evt);
                }
            });

            txtAp6.setEditable(false);
            txtAp6.setBackground(new java.awt.Color(255, 255, 255));
            txtAp6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
            txtAp6.setForeground(new java.awt.Color(102, 102, 102));
            txtAp6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            txtAp6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
            txtAp6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            txtAp6.setPreferredSize(new java.awt.Dimension(18, 18));
            txtAp6.setSelectedTextColor(new java.awt.Color(102, 102, 102));
            txtAp6.setSelectionColor(new java.awt.Color(255, 204, 51));
            txtAp6.addCaretListener(new javax.swing.event.CaretListener() {
                public void caretUpdate(javax.swing.event.CaretEvent evt) {
                    txtAp6CaretUpdate(evt);
                }
            });
            txtAp6.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    txtAp6MouseClicked(evt);
                }
            });

            txtAp7.setEditable(false);
            txtAp7.setBackground(new java.awt.Color(255, 255, 255));
            txtAp7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
            txtAp7.setForeground(new java.awt.Color(102, 102, 102));
            txtAp7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            txtAp7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
            txtAp7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            txtAp7.setPreferredSize(new java.awt.Dimension(18, 18));
            txtAp7.setSelectionColor(new java.awt.Color(255, 51, 51));
            txtAp7.addCaretListener(new javax.swing.event.CaretListener() {
                public void caretUpdate(javax.swing.event.CaretEvent evt) {
                    txtAp7CaretUpdate(evt);
                }
            });
            txtAp7.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    txtAp7MouseClicked(evt);
                }
            });

            txtAp8.setEditable(false);
            txtAp8.setBackground(new java.awt.Color(255, 255, 255));
            txtAp8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
            txtAp8.setForeground(new java.awt.Color(102, 102, 102));
            txtAp8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            txtAp8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
            txtAp8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            txtAp8.setPreferredSize(new java.awt.Dimension(18, 18));
            txtAp8.setSelectionColor(new java.awt.Color(255, 51, 51));
            txtAp8.addCaretListener(new javax.swing.event.CaretListener() {
                public void caretUpdate(javax.swing.event.CaretEvent evt) {
                    txtAp8CaretUpdate(evt);
                }
            });
            txtAp8.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    txtAp8MouseClicked(evt);
                }
            });

            txtAp9.setEditable(false);
            txtAp9.setBackground(new java.awt.Color(255, 255, 255));
            txtAp9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
            txtAp9.setForeground(new java.awt.Color(102, 102, 102));
            txtAp9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            txtAp9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
            txtAp9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            txtAp9.setPreferredSize(new java.awt.Dimension(18, 18));
            txtAp9.setSelectedTextColor(new java.awt.Color(102, 102, 102));
            txtAp9.setSelectionColor(new java.awt.Color(255, 204, 51));
            txtAp9.addCaretListener(new javax.swing.event.CaretListener() {
                public void caretUpdate(javax.swing.event.CaretEvent evt) {
                    txtAp9CaretUpdate(evt);
                }
            });
            txtAp9.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    txtAp9MouseClicked(evt);
                }
            });

            jpanel.setBackground(new java.awt.Color(2, 67, 115));

            titulo5.setBackground(new java.awt.Color(0, 102, 102));
            titulo5.setFont(new java.awt.Font("Segoe UI Semilight", 0, 36)); // NOI18N
            titulo5.setForeground(new java.awt.Color(255, 255, 255));
            titulo5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            titulo5.setText("Solicitud de Investigación Bacteriológica");
            titulo5.setToolTipText("");
            titulo5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

            lblUsu.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
            lblUsu.setForeground(new java.awt.Color(255, 255, 255));
            lblUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/User-32.png"))); // NOI18N
            lblUsu.setText("Usuario");

            javax.swing.GroupLayout jpanelLayout = new javax.swing.GroupLayout(jpanel);
            jpanel.setLayout(jpanelLayout);
            jpanelLayout.setHorizontalGroup(
                jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpanelLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(titulo5, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
            );
            jpanelLayout.setVerticalGroup(
                jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpanelLayout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblUsu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(titulo5, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                    .addContainerGap())
            );

            jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
            jLabel1.setForeground(new java.awt.Color(51, 51, 51));
            jLabel1.setText("DISA / DIRESA:");

            jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
            jLabel2.setForeground(new java.awt.Color(51, 51, 51));
            jLabel2.setText("Red de Salud:");

            jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
            jLabel3.setForeground(new java.awt.Color(51, 51, 51));
            jLabel3.setText("EESS:");

            jLabel9.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
            jLabel9.setForeground(new java.awt.Color(51, 51, 51));
            jLabel9.setText("Apellidos y Nombres:");

            jPanel9.setBackground(new java.awt.Color(255, 255, 255));
            jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

            txtPaciente.setEditable(false);
            txtPaciente.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
            txtPaciente.setForeground(new java.awt.Color(51, 51, 51));
            txtPaciente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            txtPaciente.setBorder(null);
            txtPaciente.addCaretListener(new javax.swing.event.CaretListener() {
                public void caretUpdate(javax.swing.event.CaretEvent evt) {
                    txtPacienteCaretUpdate(evt);
                }
            });

            btnBuscarHC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/Búsqueda-25.png"))); // NOI18N
            btnBuscarHC.setMnemonic('B');
            btnBuscarHC.setToolTipText("");
            btnBuscarHC.setBorderPainted(false);
            btnBuscarHC.setContentAreaFilled(false);
            btnBuscarHC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            btnBuscarHC.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnBuscarHCActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
            jPanel9.setLayout(jPanel9Layout);
            jPanel9Layout.setHorizontalGroup(
                jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addComponent(txtPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(btnBuscarHC, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
            );
            jPanel9Layout.setVerticalGroup(
                jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnBuscarHC, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            jLabel10.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
            jLabel10.setForeground(new java.awt.Color(51, 51, 51));
            jLabel10.setText("Historia Clínica");

            lblhc.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
            lblhc.setForeground(new java.awt.Color(51, 51, 51));

            jLabel12.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
            jLabel12.setForeground(new java.awt.Color(51, 51, 51));
            jLabel12.setText("Dirección");

            jLabel13.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
            jLabel13.setForeground(new java.awt.Color(51, 51, 51));
            jLabel13.setText("Referencia:");

            lblDireccion.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
            lblDireccion.setForeground(new java.awt.Color(51, 51, 51));

            jLabel15.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
            jLabel15.setForeground(new java.awt.Color(51, 51, 51));
            jLabel15.setText("Provincia:");

            lblProvincia.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
            lblProvincia.setForeground(new java.awt.Color(51, 51, 51));

            jLabel18.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
            jLabel18.setForeground(new java.awt.Color(51, 51, 51));
            jLabel18.setText("DNI");

            jLabel19.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
            jLabel19.setForeground(new java.awt.Color(51, 51, 51));
            jLabel19.setText("Edad:");

            jLabel20.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
            jLabel20.setForeground(new java.awt.Color(51, 51, 51));
            jLabel20.setText("Sexo:");

            lblDNI.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
            lblDNI.setForeground(new java.awt.Color(51, 51, 51));

            jLabel22.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
            jLabel22.setForeground(new java.awt.Color(51, 51, 51));
            jLabel22.setText("Teléfono");

            lblEdad.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
            lblEdad.setForeground(new java.awt.Color(51, 51, 51));

            lblSexo.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
            lblSexo.setForeground(new java.awt.Color(51, 51, 51));

            lblTelefono.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
            lblTelefono.setForeground(new java.awt.Color(51, 51, 51));

            jLabel27.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
            jLabel27.setForeground(new java.awt.Color(51, 51, 51));
            jLabel27.setText("Distrito:");

            lblDistrito.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
            lblDistrito.setForeground(new java.awt.Color(51, 51, 51));

            jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
            jLabel4.setForeground(new java.awt.Color(51, 51, 51));
            jLabel4.setText("Servicio:");

            jLabel5.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
            jLabel5.setForeground(new java.awt.Color(51, 51, 51));
            jLabel5.setText("Cama N°");

            lblCama.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
            lblCama.setForeground(new java.awt.Color(51, 51, 51));

            lblServicio.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
            lblServicio.setForeground(new java.awt.Color(51, 51, 51));

            jLabel7.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
            jLabel7.setForeground(new java.awt.Color(51, 51, 51));
            jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel7.setText("CHINCHA");

            lblCodHC.setText("jLabel8");

            jPanel10.setBackground(new java.awt.Color(255, 255, 255));
            jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

            txtReferencia.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
            txtReferencia.setForeground(new java.awt.Color(51, 51, 51));
            txtReferencia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            txtReferencia.setBorder(null);
            txtReferencia.addCaretListener(new javax.swing.event.CaretListener() {
                public void caretUpdate(javax.swing.event.CaretEvent evt) {
                    txtReferenciaCaretUpdate(evt);
                }
            });
            txtReferencia.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    txtReferenciaActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
            jPanel10.setLayout(jPanel10Layout);
            jPanel10Layout.setHorizontalGroup(
                jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(txtReferencia, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
            );
            jPanel10Layout.setVerticalGroup(
                jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addComponent(txtReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE))
            );

            jLabel8.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
            jLabel8.setForeground(new java.awt.Color(51, 51, 51));

            jLabel11.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
            jLabel11.setForeground(new java.awt.Color(51, 51, 51));

            jLabel14.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
            jLabel14.setForeground(new java.awt.Color(51, 51, 51));
            jLabel14.setText("Esputo:");

            jPanel4.setBackground(new java.awt.Color(255, 255, 255));
            jPanel4.setLayout(null);

            jLabel21.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
            jLabel21.setText("Paciente");
            jPanel4.add(jLabel21);
            jLabel21.setBounds(2, 0, 250, 20);

            jLabel23.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
            jLabel23.setText("_______________________________________________________________________________________________________________________________________");
            jPanel4.add(jLabel23);
            jLabel23.setBounds(0, 0, 810, 30);

            jPanel5.setBackground(new java.awt.Color(255, 255, 255));
            jPanel5.setLayout(null);

            jLabel24.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
            jLabel24.setText("Paciente");
            jPanel5.add(jLabel24);
            jLabel24.setBounds(2, 0, 250, 21);

            jLabel26.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
            jLabel26.setText("_______________________________________________________________________________________________________________________________________");
            jPanel5.add(jLabel26);
            jLabel26.setBounds(0, 10, 810, 20);

            jPanel4.add(jPanel5);
            jPanel5.setBounds(0, 0, 0, 0);

            jPanel6.setBackground(new java.awt.Color(255, 255, 255));
            jPanel6.setLayout(null);

            jLabel28.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
            jLabel28.setText("Tipo de Muestra");
            jPanel6.add(jLabel28);
            jLabel28.setBounds(2, 0, 250, 20);

            jLabel29.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
            jLabel29.setText("_______________________________________________________________________________________________________________________________________");
            jPanel6.add(jLabel29);
            jLabel29.setBounds(0, 0, 810, 30);

            jPanel7.setBackground(new java.awt.Color(255, 255, 255));
            jPanel7.setLayout(null);

            jLabel30.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
            jLabel30.setText("Paciente");
            jPanel7.add(jLabel30);
            jLabel30.setBounds(2, 0, 250, 21);

            jLabel31.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
            jLabel31.setText("_______________________________________________________________________________________________________________________________________");
            jPanel7.add(jLabel31);
            jLabel31.setBounds(0, 10, 810, 20);

            jPanel6.add(jPanel7);
            jPanel7.setBounds(0, 0, 0, 0);

            jLabel16.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
            jLabel16.setForeground(new java.awt.Color(51, 51, 51));
            jLabel16.setText("Otro:");

            jPanel11.setBackground(new java.awt.Color(255, 255, 255));
            jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

            txtReferencia1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
            txtReferencia1.setForeground(new java.awt.Color(51, 51, 51));
            txtReferencia1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            txtReferencia1.setBorder(null);
            txtReferencia1.addCaretListener(new javax.swing.event.CaretListener() {
                public void caretUpdate(javax.swing.event.CaretEvent evt) {
                    txtReferencia1CaretUpdate(evt);
                }
            });
            txtReferencia1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    txtReferencia1ActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
            jPanel11.setLayout(jPanel11Layout);
            jPanel11Layout.setHorizontalGroup(
                jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(txtReferencia1, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))
            );
            jPanel11Layout.setVerticalGroup(
                jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(txtReferencia1, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
            );

            jLabel17.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
            jLabel17.setForeground(new java.awt.Color(51, 51, 51));
            jLabel17.setText("Especificar:");

            jPanel8.setBackground(new java.awt.Color(255, 255, 255));
            jPanel8.setLayout(null);

            jLabel32.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
            jLabel32.setText("Antecedentes de Tratamiento");
            jPanel8.add(jLabel32);
            jLabel32.setBounds(2, 0, 320, 20);

            jLabel33.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
            jLabel33.setText("_______________________________________________________________________________________________________________________________________");
            jPanel8.add(jLabel33);
            jLabel33.setBounds(0, 0, 810, 30);

            jPanel12.setBackground(new java.awt.Color(255, 255, 255));
            jPanel12.setLayout(null);

            jLabel34.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
            jLabel34.setText("Paciente");
            jPanel12.add(jLabel34);
            jLabel34.setBounds(2, 0, 250, 21);

            jLabel35.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
            jLabel35.setText("_______________________________________________________________________________________________________________________________________");
            jPanel12.add(jLabel35);
            jLabel35.setBounds(0, 10, 810, 20);

            jPanel8.add(jPanel12);
            jPanel12.setBounds(0, 0, 0, 0);

            jLabel36.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
            jLabel36.setForeground(new java.awt.Color(51, 51, 51));
            jLabel36.setText("Nunca Tratado");

            jLabel37.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
            jLabel37.setForeground(new java.awt.Color(51, 51, 51));
            jLabel37.setText("Antes Tratado: Recaída");

            jLabel38.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
            jLabel38.setForeground(new java.awt.Color(51, 51, 51));
            jLabel38.setText("Abandono Recup.");

            jLabel39.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
            jLabel39.setForeground(new java.awt.Color(51, 51, 51));
            jLabel39.setText("Fracaso");

            jPanel13.setBackground(new java.awt.Color(255, 255, 255));
            jPanel13.setLayout(null);

            jLabel40.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
            jLabel40.setText("Diagnóstico");
            jPanel13.add(jLabel40);
            jLabel40.setBounds(2, 0, 250, 20);

            jLabel41.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
            jLabel41.setText("_______________________________________________________________________________________________________________________________________");
            jPanel13.add(jLabel41);
            jLabel41.setBounds(0, 0, 810, 30);

            jPanel14.setBackground(new java.awt.Color(255, 255, 255));
            jPanel14.setLayout(null);

            jLabel42.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
            jLabel42.setText("Paciente");
            jPanel14.add(jLabel42);
            jLabel42.setBounds(2, 0, 250, 21);

            jLabel43.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
            jLabel43.setText("_______________________________________________________________________________________________________________________________________");
            jPanel14.add(jLabel43);
            jLabel43.setBounds(0, 10, 810, 20);

            jPanel13.add(jPanel14);
            jPanel14.setBounds(0, 0, 0, 0);

            jLabel44.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
            jLabel44.setForeground(new java.awt.Color(51, 51, 51));
            jLabel44.setText("S.R.");

            jLabel45.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
            jLabel45.setForeground(new java.awt.Color(51, 51, 51));
            jLabel45.setText("Seg. Diagnóstico");

            txtAp10.setEditable(false);
            txtAp10.setBackground(new java.awt.Color(255, 255, 255));
            txtAp10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
            txtAp10.setForeground(new java.awt.Color(102, 102, 102));
            txtAp10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            txtAp10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
            txtAp10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            txtAp10.setPreferredSize(new java.awt.Dimension(18, 18));
            txtAp10.setSelectionColor(new java.awt.Color(255, 51, 51));
            txtAp10.addCaretListener(new javax.swing.event.CaretListener() {
                public void caretUpdate(javax.swing.event.CaretEvent evt) {
                    txtAp10CaretUpdate(evt);
                }
            });
            txtAp10.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    txtAp10MouseClicked(evt);
                }
            });

            jPanel15.setBackground(new java.awt.Color(255, 255, 255));
            jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

            txtReferencia2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
            txtReferencia2.setForeground(new java.awt.Color(51, 51, 51));
            txtReferencia2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            txtReferencia2.setBorder(null);
            txtReferencia2.addCaretListener(new javax.swing.event.CaretListener() {
                public void caretUpdate(javax.swing.event.CaretEvent evt) {
                    txtReferencia2CaretUpdate(evt);
                }
            });
            txtReferencia2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    txtReferencia2ActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
            jPanel15.setLayout(jPanel15Layout);
            jPanel15Layout.setHorizontalGroup(
                jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                    .addGap(0, 21, Short.MAX_VALUE)
                    .addComponent(txtReferencia2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
            );
            jPanel15Layout.setVerticalGroup(
                jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(txtReferencia2, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
            );

            jLabel47.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
            jLabel47.setForeground(new java.awt.Color(51, 51, 51));
            jLabel47.setText("RX Anormal");

            txtAp11.setEditable(false);
            txtAp11.setBackground(new java.awt.Color(255, 255, 255));
            txtAp11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
            txtAp11.setForeground(new java.awt.Color(102, 102, 102));
            txtAp11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            txtAp11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
            txtAp11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            txtAp11.setPreferredSize(new java.awt.Dimension(18, 18));
            txtAp11.setSelectionColor(new java.awt.Color(255, 51, 51));
            txtAp11.addCaretListener(new javax.swing.event.CaretListener() {
                public void caretUpdate(javax.swing.event.CaretEvent evt) {
                    txtAp11CaretUpdate(evt);
                }
            });
            txtAp11.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    txtAp11MouseClicked(evt);
                }
            });

            jLabel48.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
            jLabel48.setForeground(new java.awt.Color(51, 51, 51));
            jLabel48.setText("Otro");

            txtAp12.setEditable(false);
            txtAp12.setBackground(new java.awt.Color(255, 255, 255));
            txtAp12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
            txtAp12.setForeground(new java.awt.Color(102, 102, 102));
            txtAp12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            txtAp12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
            txtAp12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            txtAp12.setPreferredSize(new java.awt.Dimension(18, 18));
            txtAp12.setSelectionColor(new java.awt.Color(255, 51, 51));
            txtAp12.addCaretListener(new javax.swing.event.CaretListener() {
                public void caretUpdate(javax.swing.event.CaretEvent evt) {
                    txtAp12CaretUpdate(evt);
                }
            });
            txtAp12.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    txtAp12MouseClicked(evt);
                }
            });

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(355, 355, 355)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGap(110, 110, 110))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                            .addComponent(lblServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                                        .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblSexo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(lblCama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(lblDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(0, 0, Short.MAX_VALUE))
                                                        .addComponent(lblDistrito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(36, 36, 36)
                                    .addComponent(txtAp4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(93, 93, 93)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtAp9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel17)
                                    .addGap(18, 18, 18)
                                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(3, 3, 3)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtAp2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(49, 49, 49)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtAp10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtAp11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(62, 62, 62)
                                            .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtAp12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(227, 227, 227))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(lblProvincia, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                                                    .addComponent(lblDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(lblhc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addGap(17, 17, 17)
                                                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                            .addComponent(lblEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addGap(18, 18, 18)
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                                        .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblCodHC, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel36)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtAp6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(73, 73, 73)
                                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtAp7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(67, 67, 67)
                                        .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtAp8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(64, 64, 64)
                                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtAp5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(0, 18, Short.MAX_VALUE)))
                    .addContainerGap())
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblCodHC)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblCama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblServicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblhc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(lblDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(10, 10, 10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(lblTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblDireccion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                        .addComponent(jLabel27)
                        .addComponent(lblDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel15)
                            .addGap(6, 6, 6)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAp4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAp9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtAp6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtAp7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtAp8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtAp5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAp2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAp10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAp11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAp12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(119, 119, 119))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void txtAp2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtAp2CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAp2CaretUpdate

    private void txtAp2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAp2MouseClicked
       
            if(txtAp2.getText().equals("") && evt.getClickCount()==1){
                txtAp2.setText("X");
            }else
            if(txtAp2.getText().equals("X") && evt.getClickCount()==1){
                txtAp2.setText("");
            }

        
        
    }//GEN-LAST:event_txtAp2MouseClicked

    private void txtAp4CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtAp4CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAp4CaretUpdate

    private void txtAp4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAp4MouseClicked
      
            if(txtAp4.getText().equals("") && evt.getClickCount()==1){
                txtAp4.setText("X");
            }else
            if(txtAp4.getText().equals("X") && evt.getClickCount()==1){
                txtAp4.setText("");
            }
           
        
    }//GEN-LAST:event_txtAp4MouseClicked

    private void txtAp5CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtAp5CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAp5CaretUpdate

    private void txtAp5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAp5MouseClicked
      
            if(txtAp5.getText().equals("") && evt.getClickCount()==1){
                txtAp5.setText("X");
            }else
            if(txtAp5.getText().equals("X") && evt.getClickCount()==1){
                txtAp5.setText("");
            }
            
       
    }//GEN-LAST:event_txtAp5MouseClicked

    private void txtAp6CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtAp6CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAp6CaretUpdate

    private void txtAp6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAp6MouseClicked
        
            if(txtAp6.getText().equals("") && evt.getClickCount()==1){
                txtAp6.setText("X");
            }else
            if(txtAp6.getText().equals("X") && evt.getClickCount()==1){
                txtAp6.setText("");
            }
            
        
    }//GEN-LAST:event_txtAp6MouseClicked

    private void txtAp7CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtAp7CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAp7CaretUpdate

    private void txtAp7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAp7MouseClicked
    
            if(txtAp7.getText().equals("") && evt.getClickCount()==1){
                txtAp7.setText("X");
            }else
            if(txtAp7.getText().equals("X") && evt.getClickCount()==1){
                txtAp7.setText("");
            }
       
        
    }//GEN-LAST:event_txtAp7MouseClicked

    private void txtAp8CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtAp8CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAp8CaretUpdate

    private void txtAp8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAp8MouseClicked
      
            if(txtAp8.getText().equals("") && evt.getClickCount()==1){
                txtAp8.setText("X");

            }else
            if(txtAp8.getText().equals("X") && evt.getClickCount()==1){
                txtAp8.setText("");
            }
         
        
    }//GEN-LAST:event_txtAp8MouseClicked

    private void txtAp9CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtAp9CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAp9CaretUpdate

    private void txtAp9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAp9MouseClicked
        
            if(txtAp9.getText().equals("") && evt.getClickCount()==1){
                txtAp9.setText("X");

            }else
            if(txtAp9.getText().equals("X") && evt.getClickCount()==1){
                txtAp9.setText("");

            }
        
    }//GEN-LAST:event_txtAp9MouseClicked

    private void btnBuscarHCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarHCActionPerformed
  buscar_HC.setVisible(true);
        txtbuscarHC.setText("");
        LAB_HC_cargar();
        LAB_HC_formato();      
    }//GEN-LAST:event_btnBuscarHCActionPerformed

    private void txtPacienteCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtPacienteCaretUpdate

    }//GEN-LAST:event_txtPacienteCaretUpdate

    private void btnBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar1ActionPerformed
        // TODO add your handling code here:
        String consulta="";
         try {
             String titulos[]={"N°","Codigo","N° H.C.","Paciente","DNI","Telefono","Dirección","Fecha de Nac.","Edad","Sexo"
             ,"Distrito","Provincia","Departamento"};
            m=new DefaultTableModel(null,titulos);
            JTable p=new JTable(m);
            String fila[]=new String[13];

            LAB_Clasificacion_Examen obj=new LAB_Clasificacion_Examen();
         consulta="exec sp_BuscarHC ?";
        
        PreparedStatement cmd = obj.getCn().prepareStatement(consulta);
            cmd.setString(1, txtbuscarHC.getText());
        ResultSet r=cmd.executeQuery();
        int c=1;
        while(r.next()){
            fila[0]=String.valueOf(c)+"º";
            fila[1]=r.getString(1);
            fila[2]=r.getString(2);
            fila[3]=r.getString(3);
            fila[4]=r.getString(4);
            fila[5]=r.getString(5);
            fila[6]=r.getString(6);
            fila[7]=r.getString(7);
            fila[8]=r.getString(8);
            fila[9]=r.getString(9);
            fila[10]=r.getString(10);
            fila[11]=r.getString(11);
                m.addRow(fila);
                c++;
            }
            tb_HC.setModel(m);
            TableRowSorter<TableModel> elQueOrdena=new TableRowSorter<TableModel>(m);
            tb_HC.setRowSorter(elQueOrdena);
            this.tb_HC.setModel(m);
            
            LAB_HC_formato();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(rootPane, "Error en la tabla");
    }
    }//GEN-LAST:event_btnBuscar1ActionPerformed

    private void txtbuscarHCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarHCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarHCActionPerformed

    private void txtbuscarHCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarHCKeyPressed
        if(evt.getExtendedKeyCode()==KeyEvent.VK_DOWN){
            tb_HC.getSelectionModel().setSelectionInterval(0, 0);
            tb_HC.requestFocus();
        }
    }//GEN-LAST:event_txtbuscarHCKeyPressed

    private void txtbuscarHCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarHCKeyTyped
        char tecla= evt.getKeyChar();
        if(tecla==KeyEvent.VK_ENTER){
            btnBuscar1.doClick();
        }
    }//GEN-LAST:event_txtbuscarHCKeyTyped

    private void tb_HCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_HCMouseClicked

    }//GEN-LAST:event_tb_HCMouseClicked

    private void tb_HCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tb_HCKeyPressed
        char tecla= evt.getKeyChar();
        if(tecla==KeyEvent.VK_ENTER){
            try{
                if(tb_HC.getRowCount()>0){
                buscar_HC.setVisible(false);
                int filaselec=tb_HC.getSelectedRow();

                lblCodHC.setText(tb_HC.getValueAt(filaselec, 1).toString());
                lblhc.setText(tb_HC.getValueAt(filaselec, 2).toString());
                txtPaciente.setText(tb_HC.getValueAt(filaselec, 3).toString());
                lblDNI.setText(tb_HC.getValueAt(filaselec, 4).toString());
                lblTelefono.setText(tb_HC.getValueAt(filaselec, 5).toString());
                lblDireccion.setText(tb_HC.getValueAt(filaselec, 6).toString());
                lblEdad.setText(tb_HC.getValueAt(filaselec, 8).toString());
                lblSexo.setText(tb_HC.getValueAt(filaselec, 9).toString());
                lblDistrito.setText(tb_HC.getValueAt(filaselec, 10).toString());
                lblProvincia.setText(tb_HC.getValueAt(filaselec, 11).toString());
                
              
                //HOSPITALIZACION
                LAB_Toma_Muestra_Detalle hosp=new LAB_Toma_Muestra_Detalle();
                if(hosp.LAB_Toma_Muestra_Hospitalizacion_ver(tb_HC.getValueAt(filaselec, 1).toString())>0){
                   LAB_Toma_Muestra_Detalle td=new LAB_Toma_Muestra_Detalle();
                 String serv_hospi=  td.LAB_Toma_Muestra_Hospi_Servicio(tb_HC.getValueAt(filaselec, 1).toString());
                lblServicio.setText(serv_hospi);
                
                LAB_Toma_Muestra_Detalle td1=new LAB_Toma_Muestra_Detalle();
                String cama=  td1.LAB_Toma_Muestra_Hospi_cama(tb_HC.getValueAt(filaselec, 1).toString());
                lblCama.setText(cama);
                
                }else{
                    
                   lblServicio.setText("-");
                   lblCama.setText("-");
                }
                }
            }
            catch(Exception ex)
            {
                System.out.println("Error: " + ex.getMessage());
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_HCKeyPressed

    private void txtReferenciaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtReferenciaCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReferenciaCaretUpdate

    private void txtReferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReferenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReferenciaActionPerformed

    private void txtAp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAp2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAp2ActionPerformed

    private void txtReferencia1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtReferencia1CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReferencia1CaretUpdate

    private void txtReferencia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReferencia1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReferencia1ActionPerformed

    private void txtAp4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAp4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAp4ActionPerformed

    private void txtAp10CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtAp10CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAp10CaretUpdate

    private void txtAp10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAp10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAp10MouseClicked

    private void txtReferencia2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtReferencia2CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReferencia2CaretUpdate

    private void txtReferencia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReferencia2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReferencia2ActionPerformed

    private void txtAp11CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtAp11CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAp11CaretUpdate

    private void txtAp11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAp11MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAp11MouseClicked

    private void txtAp12CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtAp12CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAp12CaretUpdate

    private void txtAp12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAp12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAp12MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_SOLICITUD_INVESTIGACION_BACT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_SOLICITUD_INVESTIGACION_BACT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_SOLICITUD_INVESTIGACION_BACT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_SOLICITUD_INVESTIGACION_BACT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_SOLICITUD_INVESTIGACION_BACT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar1;
    private javax.swing.JButton btnBuscarHC;
    private javax.swing.JDialog buscar_HC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpanel;
    private javax.swing.JPanel jpanel3;
    private javax.swing.JLabel lblCama;
    private javax.swing.JLabel lblCodHC;
    private javax.swing.JLabel lblDNI;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblDistrito;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblProvincia;
    private javax.swing.JLabel lblServicio;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTelefono;
    public static javax.swing.JLabel lblUsu;
    private javax.swing.JLabel lblhc;
    public static javax.swing.JTable tb_HC;
    private javax.swing.JLabel titulo5;
    private javax.swing.JLabel titulo8;
    public static javax.swing.JTextField txtAp10;
    public static javax.swing.JTextField txtAp11;
    public static javax.swing.JTextField txtAp12;
    public static javax.swing.JTextField txtAp2;
    public static javax.swing.JTextField txtAp4;
    public static javax.swing.JTextField txtAp5;
    public static javax.swing.JTextField txtAp6;
    public static javax.swing.JTextField txtAp7;
    public static javax.swing.JTextField txtAp8;
    public static javax.swing.JTextField txtAp9;
    public static javax.swing.JTextField txtPaciente;
    public static javax.swing.JTextField txtReferencia;
    public static javax.swing.JTextField txtReferencia1;
    public static javax.swing.JTextField txtReferencia2;
    private javax.swing.JTextField txtbuscarHC;
    // End of variables declaration//GEN-END:variables
}
