/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.LABORATORIO;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import modelos.LABORATORIO.LAB_Clasificacion_Examen;
/**
 *
 * @author PC-SISTEMA
 */
public class HC extends javax.swing.JInternalFrame {
    private JComponent Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).getNorthPane();
private Dimension DimensionBarra = null; 
DefaultTableModel m;
    /**
     * Creates new form HC
     */
    public HC() {
        initComponents();
        LAB_HC1_cargar();
        LAB_HC1_formato();
         txtbuscarHC1.setText("");
         QuitarLaBarraTitulo();
        getContentPane().setBackground(Color.white); 
    }
    
    public void QuitarLaBarraTitulo()
    { 
    Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).getNorthPane(); 
    DimensionBarra = Barra.getPreferredSize(); 
    Barra.setSize(0,0); 
    Barra.setPreferredSize(new Dimension(0,0)); 
    repaint(); 
    }
  public void LAB_HC1_cargar(){
    try {
             String titulos[]={"N°","N° H.C.","Paciente","Dirección","DNI","Sexo","Fecha de Nac.","Edad","Código"};
            m=new DefaultTableModel(null,titulos);
            JTable p=new JTable(m);
            String fila[]=new String[9];

            LAB_Clasificacion_Examen obj=new LAB_Clasificacion_Examen();
        String consulta="exec Caja_BuscarHC ?";
        
        PreparedStatement cmd = obj.getCn().prepareStatement(consulta);
            cmd.setString(1, "");
        ResultSet r=cmd.executeQuery();
        int c=1;
        while(r.next()){
            fila[0]=String.valueOf(c)+"°";
            fila[1]=r.getString(1);
            fila[2]=r.getString(2);
            fila[3]=r.getString(3);
            fila[4]=r.getString(4);
            fila[5]=r.getString(5);
            fila[6]=r.getString(6);
             fila[7]=r.getString(7);
              fila[8]=r.getString(8);
                m.addRow(fila);
                c++;
            }
            tb_HC1.setModel(m);
            TableRowSorter<TableModel> elQueOrdena=new TableRowSorter<TableModel>(m);
            tb_HC1.setRowSorter(elQueOrdena);
            this.tb_HC1.setModel(m);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(rootPane, "Error en la tabla");
    }
}
     public void LAB_HC1_formato(){
    tb_HC1.getColumnModel().getColumn(0).setPreferredWidth(40);
    tb_HC1.getColumnModel().getColumn(1).setPreferredWidth(100);
    tb_HC1.getColumnModel().getColumn(2).setPreferredWidth(230);
    tb_HC1.getColumnModel().getColumn(3).setPreferredWidth(180);
    tb_HC1.getColumnModel().getColumn(4).setPreferredWidth(100);
    tb_HC1.getColumnModel().getColumn(5).setPreferredWidth(80);
    tb_HC1.getColumnModel().getColumn(6).setPreferredWidth(150);
    tb_HC1.getColumnModel().getColumn(7).setPreferredWidth(100);
    
            //Ocultar    
    tb_HC1.getColumnModel().getColumn(8).setMinWidth(0);
    tb_HC1.getColumnModel().getColumn(8).setMaxWidth(0);
    tb_HC1.getSelectionModel().setSelectionInterval(0, 0);
            tb_HC1.requestFocus();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanel3 = new javax.swing.JPanel();
        titulo8 = new javax.swing.JLabel();
        txtbuscarHC1 = new javax.swing.JTextField();
        btnBuscar2 = new javax.swing.JButton();
        jLabel42 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tb_HC1 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false; //Disallow the editing of any cell
            }};

            setBackground(new java.awt.Color(255, 255, 255));
            setBorder(javax.swing.BorderFactory.createCompoundBorder());
            setVisible(true);

            jpanel3.setBackground(new java.awt.Color(2, 67, 115));

            titulo8.setBackground(new java.awt.Color(0, 102, 102));
            titulo8.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
            titulo8.setForeground(new java.awt.Color(255, 255, 255));
            titulo8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            titulo8.setText("Historia Clínica");
            titulo8.setToolTipText("");
            titulo8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

            javax.swing.GroupLayout jpanel3Layout = new javax.swing.GroupLayout(jpanel3);
            jpanel3.setLayout(jpanel3Layout);
            jpanel3Layout.setHorizontalGroup(
                jpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(titulo8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
            jpanel3Layout.setVerticalGroup(
                jpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(titulo8, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
            );

            txtbuscarHC1.setForeground(new java.awt.Color(0, 51, 51));
            txtbuscarHC1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    txtbuscarHC1ActionPerformed(evt);
                }
            });
            txtbuscarHC1.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    txtbuscarHC1KeyPressed(evt);
                }
                public void keyTyped(java.awt.event.KeyEvent evt) {
                    txtbuscarHC1KeyTyped(evt);
                }
            });

            btnBuscar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/view.gif"))); // NOI18N
            btnBuscar2.setBorder(null);
            btnBuscar2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnBuscar2ActionPerformed(evt);
                }
            });

            jLabel42.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
            jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel42.setText("Búsqueda por H.C / Paciente / DNI");

            tb_HC1.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
                },
                new String [] {
                    "Title 1", "Title 2", "Title 3", "Title 4"
                }
            ));
            tb_HC1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
            tb_HC1.setRowHeight(25);
            tb_HC1.getTableHeader().setReorderingAllowed(false);
            tb_HC1.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    tb_HC1MouseClicked(evt);
                }
            });
            tb_HC1.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    tb_HC1KeyPressed(evt);
                }
            });
            jScrollPane6.setViewportView(tb_HC1);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createSequentialGroup()
                    .addGap(301, 301, 301)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtbuscarHC1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(btnBuscar2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 892, Short.MAX_VALUE)
                    .addContainerGap())
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jpanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtbuscarHC1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscar2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(2, 2, 2)
                    .addComponent(jLabel42)
                    .addGap(3, 3, 3)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void txtbuscarHC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarHC1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarHC1ActionPerformed

    private void txtbuscarHC1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarHC1KeyPressed
        if(evt.getExtendedKeyCode()==KeyEvent.VK_DOWN){
            tb_HC1.getSelectionModel().setSelectionInterval(0, 0);
            tb_HC1.requestFocus();
        }
    }//GEN-LAST:event_txtbuscarHC1KeyPressed

    private void txtbuscarHC1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarHC1KeyTyped
        char tecla= evt.getKeyChar();
        if(tecla==KeyEvent.VK_ENTER){
            btnBuscar2.doClick();
        }
    }//GEN-LAST:event_txtbuscarHC1KeyTyped

    private void btnBuscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar2ActionPerformed
        // TODO add your handling code here:
        String consulta="";
        try {
            tb_HC1.setModel(new DefaultTableModel());
            String titulos[]={"N°","N° H.C.","Paciente","Dirección","DNI","Sexo","Fecha de Nac.","Edad","COdigo"};
            m=new DefaultTableModel(null,titulos);
            JTable p=new JTable(m);
            String fila[]=new String[9];

            LAB_Clasificacion_Examen obj=new LAB_Clasificacion_Examen();
            consulta="exec Caja_BuscarHC ?";

            PreparedStatement cmd = obj.getCn().prepareStatement(consulta);
            cmd.setString(1, txtbuscarHC1.getText());
            ResultSet r= cmd.executeQuery();
            int c=1;
            while(r.next()){
                fila[0]=String.valueOf(c)+"°";
                fila[1]=r.getString(1);
                fila[2]=r.getString(2);
                fila[3]=r.getString(3);
                fila[4]=r.getString(4);
                fila[5]=r.getString(5);
                fila[6]=r.getString(6);
                fila[7]=r.getString(7);
                fila[8]=r.getString(8);
                m.addRow(fila);
                c++;
            }
            tb_HC1.setModel(m);
            TableRowSorter<TableModel> elQueOrdena=new TableRowSorter<TableModel>(m);
            tb_HC1.setRowSorter(elQueOrdena);
            this.tb_HC1.setModel(m);

            LAB_HC1_formato();

        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnBuscar2ActionPerformed

    private void tb_HC1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_HC1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_HC1MouseClicked

    private void tb_HC1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tb_HC1KeyPressed
        char tecla= evt.getKeyChar();
        if(tecla==KeyEvent.VK_ENTER){
            try{
                
              frm_LAB_ENTREGA_RESULTADO.btnCerrarDialog.doClick();
                int filaselec=tb_HC1.getSelectedRow();

               frm_LAB_ENTREGA_RESULTADO. txtPacienteRecep.setText(tb_HC1.getValueAt(filaselec, 2).toString());
                frm_LAB_ENTREGA_RESULTADO.lblid_hc.setText(tb_HC1.getValueAt(filaselec, 8).toString());
            }
            catch(Exception ex)
            {
                System.out.println("Error: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_tb_HC1KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar2;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JPanel jpanel3;
    public static javax.swing.JTable tb_HC1;
    private javax.swing.JLabel titulo8;
    private javax.swing.JTextField txtbuscarHC1;
    // End of variables declaration//GEN-END:variables
}
