

SELECT * FROM SISTEMA_UNIDAD_EJECUTORA
SELECT * FROM CAJA_EMPRESA_JERARQUIA_PAGO
select * from CUENTAS_POR_PAGAR_FACTURAS_CABECERA
SELECT * FROM CUENTAS_POR_PAGAR_NOTA_CREDITO

alter procedure sp_CUENTAS_POR_PAGAR_NOTA_CREDITO_reporte
@cnc_id bigint
as
SELECT NC.CNC_ID,NC.CNC_SERIE+'-'+NC.CNC_CORRELATIVO as sc_nc,NC.CNC_FECHA_EMISION,FC.CPF_ID,
substring (CPF_DOCUMENTO,0,3) AS FAC_BOL,
FC.CPF_SERIE+'-'+FC.CPF_CORRELATIVO as sc_factura,FC.CPF_FECHA_EMISION,EJ.repre_empre_jerar,
 SUBSTRING(EJ.tipo_documento,CHARINDEX(' ',EJ.tipo_documento)+1,LEN(EJ.tipo_documento))
AS TIPO_DOCUMENTO,EJ.nro_documento,FC.CPF_TIPO_MONEDA,NC.CNC_DESCRIPCION,
(SELECT TOP 1 UNIDAD FROM SISTEMA_UNIDAD_EJECUTORA) AS UNIDAD,
(SELECT TOP 1 DIRECCION FROM SISTEMA_UNIDAD_EJECUTORA)AS DIRECCION,
(SELECT TOP 1 RUC FROM SISTEMA_UNIDAD_EJECUTORA) AS RUC
FROM CUENTAS_POR_PAGAR_FACTURAS_CABECERA FC,CUENTAS_POR_PAGAR_NOTA_CREDITO NC,
CAJA_EMPRESA_JERARQUIA_PAGO EJ 
WHERE FC.CPF_ID=NC.CPF_ID AND EJ.cod_empre_jerar=FC.cod_empre_jerar 
and nc.CNC_ID=@cnc_id
go

exec sp_CUENTAS_POR_PAGAR_NOTA_CREDITO_reporte 33 


ALTER PROCEDURE sp_CUENTAS_POR_PAGAR_NOTA_CREDITO_listar
@buscar varchar(20),
@tipo char(1)
as
if(@tipo=1)--LISTADO
begin
SELECT NC.CNC_ID,NC.CNC_SERIE+'-'+NC.CNC_CORRELATIVO,NC.CNC_FECHA_EMISION,FC.CPF_ID,
FC.CPF_SERIE+'-'+FC.CPF_CORRELATIVO,FC.CPF_FECHA_EMISION,EJ.repre_empre_jerar,ej.correo,
EJ.tipo_documento,EJ.nro_documento,FC.CPF_TIPO_MONEDA,NC.CNC_DESCRIPCION
FROM CUENTAS_POR_PAGAR_FACTURAS_CABECERA FC,CUENTAS_POR_PAGAR_NOTA_CREDITO NC,
CAJA_EMPRESA_JERARQUIA_PAGO EJ 
WHERE FC.CPF_ID=NC.CPF_ID AND EJ.cod_empre_jerar=FC.cod_empre_jerar 
end
if(@tipo=2)--todo
begin
SELECT NC.CNC_ID,NC.CNC_SERIE+'-'+NC.CNC_CORRELATIVO,NC.CNC_FECHA_EMISION,FC.CPF_ID,
FC.CPF_SERIE+'-'+FC.CPF_CORRELATIVO,FC.CPF_FECHA_EMISION,EJ.repre_empre_jerar,ej.correo,
EJ.tipo_documento,EJ.nro_documento,FC.CPF_TIPO_MONEDA,NC.CNC_DESCRIPCION
FROM CUENTAS_POR_PAGAR_FACTURAS_CABECERA FC,CUENTAS_POR_PAGAR_NOTA_CREDITO NC,
CAJA_EMPRESA_JERARQUIA_PAGO EJ
WHERE FC.CPF_ID=NC.CPF_ID AND EJ.cod_empre_jerar=FC.cod_empre_jerar 
AND ej.nro_documento like @buscar+'%'
END
if(@tipo=3)--factura
begin
SELECT NC.CNC_ID,NC.CNC_SERIE+'-'+NC.CNC_CORRELATIVO,NC.CNC_FECHA_EMISION,FC.CPF_ID,
FC.CPF_SERIE+'-'+FC.CPF_CORRELATIVO,FC.CPF_FECHA_EMISION,EJ.repre_empre_jerar,ej.correo,
EJ.tipo_documento,EJ.nro_documento,FC.CPF_TIPO_MONEDA,NC.CNC_DESCRIPCION
FROM CUENTAS_POR_PAGAR_FACTURAS_CABECERA FC,CUENTAS_POR_PAGAR_NOTA_CREDITO NC,
CAJA_EMPRESA_JERARQUIA_PAGO EJ
WHERE FC.CPF_ID=NC.CPF_ID AND EJ.cod_empre_jerar=FC.cod_empre_jerar 
AND ej.nro_documento like @buscar+'%' and fc.CPF_DOCUMENTO='01 FACTURA'
end
if(@tipo=4)--boleta
begin
SELECT NC.CNC_ID,NC.CNC_SERIE+'-'+NC.CNC_CORRELATIVO,NC.CNC_FECHA_EMISION,FC.CPF_ID,
FC.CPF_SERIE+'-'+FC.CPF_CORRELATIVO,FC.CPF_FECHA_EMISION,EJ.repre_empre_jerar,ej.correo,
EJ.tipo_documento,EJ.nro_documento,FC.CPF_TIPO_MONEDA,NC.CNC_DESCRIPCION
FROM CUENTAS_POR_PAGAR_FACTURAS_CABECERA FC,CUENTAS_POR_PAGAR_NOTA_CREDITO NC,
CAJA_EMPRESA_JERARQUIA_PAGO EJ
WHERE FC.CPF_ID=NC.CPF_ID AND EJ.cod_empre_jerar=FC.cod_empre_jerar 
AND ej.nro_documento like @buscar+'%' and fc.CPF_DOCUMENTO='03 BOLETA'
end
GO

EXEC sp_CUENTAS_POR_PAGAR_NOTA_CREDITO_listar '','1'