/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import servicios.Conexion;
import static vista.SALA_OPERACIONES.frm_SALA_OPERACION_CONDICION.fechaActual;

/**
 *
 * @author USUARIO
 */
public class Asignar_CIE10 extends javax.swing.JFrame implements Runnable{
Conexion conectar=new Conexion();
Connection con;
String hora, minutos, segundos, ampm;
Calendar calendario;
Thread h1;
CallableStatement cst;
ResultSet r;
Statement st;
    /**
     * Creates new form Asignar_CIE10
     */
    public Asignar_CIE10() {
        initComponents();
        con=conectar.conectar();
        setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.white);
        forma_pago.setLocationRelativeTo(null);
        forma_pago.getContentPane().setBackground(Color.white);
        CIE10.setLocationRelativeTo(null);
        CIE10.getContentPane().setBackground(Color.white);
        //fecha y hora
        h1 = new Thread(this);
        h1.start();
        Calendar cal=Calendar.getInstance();          
        lblFecha.setText(fechaActual());
        
        cargar_Forma_Pago();
        cargar_CIE10();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        forma_pago = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        txtBuscarFP = new javax.swing.JTextField();
        btn_BuscarFP = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_FP = new javax.swing.JTable();
        CIE10 = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbCIE10 = new javax.swing.JTable();
        txtBuscarCIE10 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        btnBuscarCIE10 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jpanel = new javax.swing.JPanel();
        titulo5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        lblUsu = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtFP = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtCIE10 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        txtCIE10Desc = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        forma_pago.setMaximumSize(new java.awt.Dimension(380, 450));
        forma_pago.setMinimumSize(new java.awt.Dimension(380, 450));
        forma_pago.setPreferredSize(new java.awt.Dimension(380, 450));

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel2.setText("Forma de Pago");

        txtBuscarFP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarFPKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarFPKeyTyped(evt);
            }
        });

        btn_BuscarFP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/Búsqueda-20.png"))); // NOI18N
        btn_BuscarFP.setContentAreaFilled(false);
        btn_BuscarFP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarFPActionPerformed(evt);
            }
        });

        tb_FP = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Disallow the editing of any cell
            }
        };
        tb_FP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_FP.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tb_FP.setSelectionBackground(new java.awt.Color(255, 102, 0));
        tb_FP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tb_FPKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tb_FP);

        javax.swing.GroupLayout forma_pagoLayout = new javax.swing.GroupLayout(forma_pago.getContentPane());
        forma_pago.getContentPane().setLayout(forma_pagoLayout);
        forma_pagoLayout.setHorizontalGroup(
            forma_pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forma_pagoLayout.createSequentialGroup()
                .addGroup(forma_pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(forma_pagoLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel2))
                    .addGroup(forma_pagoLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(txtBuscarFP, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btn_BuscarFP, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(forma_pagoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        forma_pagoLayout.setVerticalGroup(
            forma_pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forma_pagoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(forma_pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_BuscarFP)
                    .addGroup(forma_pagoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(29, 29, 29)
                        .addComponent(txtBuscarFP, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                .addContainerGap())
        );

        CIE10.setMinimumSize(new java.awt.Dimension(400, 500));
        CIE10.setPreferredSize(new java.awt.Dimension(400, 500));

        tbCIE10 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Disallow the editing of any cell
            }
        };
        tbCIE10.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbCIE10.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tbCIE10.setSelectionBackground(new java.awt.Color(255, 102, 0));
        tbCIE10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbCIE10KeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(tbCIE10);

        txtBuscarCIE10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        txtBuscarCIE10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarCIE10KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarCIE10KeyTyped(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        jLabel30.setText("BUSQUEDA");

        btnBuscarCIE10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/Search-16.png"))); // NOI18N
        btnBuscarCIE10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnBuscarCIE10.setContentAreaFilled(false);
        btnBuscarCIE10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCIE10ActionPerformed(evt);
            }
        });

        jLabel31.setText("Diagnostico:");

        javax.swing.GroupLayout CIE10Layout = new javax.swing.GroupLayout(CIE10.getContentPane());
        CIE10.getContentPane().setLayout(CIE10Layout);
        CIE10Layout.setHorizontalGroup(
            CIE10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CIE10Layout.createSequentialGroup()
                .addGroup(CIE10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CIE10Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel30))
                    .addGroup(CIE10Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(CIE10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(CIE10Layout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBuscarCIE10, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(btnBuscarCIE10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        CIE10Layout.setVerticalGroup(
            CIE10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CIE10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel30)
                .addGap(18, 18, 18)
                .addGroup(CIE10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarCIE10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCIE10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpanel.setBackground(new java.awt.Color(204, 102, 0));

        titulo5.setBackground(new java.awt.Color(0, 102, 102));
        titulo5.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        titulo5.setForeground(new java.awt.Color(255, 255, 255));
        titulo5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo5.setText("CIE10");
        titulo5.setToolTipText("");
        titulo5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel14.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Fecha:");

        lblFecha.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(255, 255, 255));
        lblFecha.setText("00/00/00");

        jLabel15.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Hora:");

        lblHora.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        lblHora.setForeground(new java.awt.Color(255, 255, 255));
        lblHora.setText("00:00:00");

        lblUsu.setFont(new java.awt.Font("Palatino Linotype", 1, 13)); // NOI18N
        lblUsu.setForeground(new java.awt.Color(255, 255, 255));
        lblUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/User-32.png"))); // NOI18N
        lblUsu.setText("Usuario");

        btnNuevo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/Documento-32.png"))); // NOI18N
        btnNuevo.setMnemonic('N');
        btnNuevo.setToolTipText("Nuevo (Alt+N)");
        btnNuevo.setContentAreaFilled(false);
        btnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnguardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/Guardar-32.png"))); // NOI18N
        btnguardar.setMnemonic('G');
        btnguardar.setToolTipText("Guardar (Alt-G)");
        btnguardar.setContentAreaFilled(false);
        btnguardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanelLayout = new javax.swing.GroupLayout(jpanel);
        jpanel.setLayout(jpanelLayout);
        jpanelLayout.setHorizontalGroup(
            jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelLayout.createSequentialGroup()
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(titulo5))
                .addGap(599, 599, 599)
                .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpanelLayout.createSequentialGroup()
                        .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHora)
                            .addComponent(lblFecha))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpanelLayout.setVerticalGroup(
            jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelLayout.createSequentialGroup()
                .addComponent(titulo5)
                .addGap(2, 2, 2)
                .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnguardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(lblFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(lblHora))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsu)
                .addContainerGap())
        );

        jLabel1.setText("FORMA DE PAGO:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/Búsqueda-20.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("CIE10:");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/Búsqueda-20.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(jTable1);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/mas.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/menos16x16.png"))); // NOI18N
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(74, 74, 74)
                        .addComponent(txtCIE10, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtCIE10Desc)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFP, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton3)
                                    .addComponent(jButton4))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFP, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCIE10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(jButton2)
                    .addComponent(txtCIE10Desc, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jButton3)
                        .addGap(32, 32, 32)
                        .addComponent(jButton4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        /*deshabilitar();
        limpiar();
        btnguardar.setEnabled(true);
        txtCondicion.requestFocus();*/
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        /*ImageIcon i=new ImageIcon(this.getClass().getResource("/imagenes/iconos/guardar16x16.png"));
        SDO_CONDICION C=new SDO_CONDICION();
        SDO_CONDICION C1=new SDO_CONDICION();
        SDO_CONDICION C2=new SDO_CONDICION();
        try{
            if(txtGM.getText().equalsIgnoreCase("G")){
                if(txtCondicion.getText().equalsIgnoreCase("")){
                    JOptionPane.showMessageDialog(rootPane, "Verifique si ha ingresado todos los campos");
                }
                else if(C.SDO_CONDICION_Ver(txtCondicion.getText())>0){
                    JOptionPane.showMessageDialog(rootPane, "El registro ya existe\nIntente nuevamente");
                    txtCondicion.setText("");
                    txtCondicion.requestFocus();
                }else{

                    int guardar = JOptionPane.showConfirmDialog(this, "¿Está seguro que desea GUARDAR los datos?",
                        "Atención", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,i);
                    if(guardar == 0 ){
                        SDO_CONDICION cg = new SDO_CONDICION();
                        cg.setID_CONDICION(txtCodigo.getText());
                        cg.setDESCRIP_CONDICION(txtCondicion.getText());
                        cg.setNOM_USU(lblUsu.getText());

                        if(cg.SDO_CONDICION_Guardar()){
                            JOptionPane.showMessageDialog(null, "Datos Guardados");
                            limpiar();
                            deshabilitar();
                            txtGM.setText("G");
                        }
                        else{
                            JOptionPane.showMessageDialog(this, "El registro ya existe\nIntente nuevamente");

                        }}
                    }}else{
                        if(txtCondicion.getText().equalsIgnoreCase("")){
                            JOptionPane.showMessageDialog(rootPane, "Verifique si ha ingresado todos los campos");
                        }
                        else if(C1.SDO_CONDICION_Codigo(txtCondicion.getText()).equalsIgnoreCase(txtCodigo.getText())==false && C2.SDO_CONDICION_Ver(txtCondicion.getText())>0 ){
                            JOptionPane.showMessageDialog(rootPane, "El registro ya existe\nIntente nuevamente");
                            txtCondicion.setText("");
                            txtCondicion.requestFocus();
                        }else{
                            int modificar = JOptionPane.showConfirmDialog(this, "¿Está seguro que desea MODIFICAR los datos?",
                                "Atención", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,i);
                            if(modificar == 0 ){
                                SDO_CONDICION cm= new SDO_CONDICION();
                                cm.setID_CONDICION(txtCodigo.getText());
                                cm.setDESCRIP_CONDICION(txtCondicion.getText());
                                cm.setNOM_USU(lblUsu.getText());

                                if(cm.SDO_CONDICION_Modificar()){
                                    JOptionPane.showMessageDialog(this, "Datos Modificados");
                                    limpiar();
                                    deshabilitar();
                                    txtGM.setText("G");
                                }
                                else{
                                    JOptionPane.showMessageDialog(this, "El registro ya existe\nIntente nuevamente");

                                }}
                            }}}catch(Exception e) {
                                JOptionPane.showMessageDialog(this, "Ingrese todos los campos");

                            }*/
    }//GEN-LAST:event_btnguardarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    forma_pago.setVisible(true);  
    cargar_Forma_Pago();// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_BuscarFPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarFPActionPerformed
        try{
            String condicion =txtBuscarFP.getText().toString();

            DefaultTableModel tabla= new DefaultTableModel();

            tabla.addColumn("Código");
            tabla.addColumn("Forma de Pago");
            tabla.addColumn("Descripción");
            cst=con.prepareCall("{call Caja_Jerarquia_BUSCAR(?)}");
            cst.setString(1, condicion);
            r=cst.executeQuery();
            while (r.next()){
                Object dato[]=new  Object[3];
                for (int i=0; i<3; i++){
                    dato[i]=r.getString(i+1);

                }
                tabla.addRow(dato);
            }

            this.tb_FP.setModel(tabla);

            formato_FP();
            txtBuscarFP.setText("");
            tb_FP.getSelectionModel().setSelectionInterval(0, 0);
            tb_FP.requestFocus();
        }catch (Exception e){}
    }//GEN-LAST:event_btn_BuscarFPActionPerformed

    private void txtBuscarFPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarFPKeyPressed
        if(evt.getExtendedKeyCode()==KeyEvent.VK_DOWN){
            tb_FP.getSelectionModel().setSelectionInterval(0, 0);
            tb_FP.requestFocus();
        }
    }//GEN-LAST:event_txtBuscarFPKeyPressed

    private void txtBuscarFPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarFPKeyTyped
        char tecla= evt.getKeyChar();
        if(tecla==KeyEvent.VK_ENTER){
            btn_BuscarFP.doClick();
        }
    }//GEN-LAST:event_txtBuscarFPKeyTyped

    private void tb_FPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tb_FPKeyPressed
         char teclaPresionada = evt.getKeyChar();

        if(teclaPresionada==KeyEvent.VK_ENTER &&
            this.tb_FP.getRowCount() == 0 &&
            this.tb_FP.getSelectedRow() == -1){

            JOptionPane.showMessageDialog(rootPane, "La tabla esta vacia");

        }else
        if(teclaPresionada==KeyEvent.VK_ENTER &&
            this.tb_FP.getRowCount() != 0 &&
            this.tb_FP.getSelectedRow() != -1){
            int fila = tb_FP.getSelectedRow();

           forma_pago.setVisible(false);

            txtFP.setText(String.valueOf(tb_FP.getValueAt(fila, 1)));
            //btnmodificar.setEnabled(true);
            //btneliminar.setEnabled(true);
            String u=lblUsu.getText();
            lblUsu.setText(u);
            //txtFP.setEnabled(false);
           
        }
    }//GEN-LAST:event_tb_FPKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CIE10.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tbCIE10KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbCIE10KeyPressed
         char teclaPresionada = evt.getKeyChar();

        if(teclaPresionada==KeyEvent.VK_ENTER &&
            this.tbCIE10.getRowCount() == 0 &&
            this.tbCIE10.getSelectedRow() == -1){

            JOptionPane.showMessageDialog(rootPane, "La tabla esta vacia");

        }else
        if(teclaPresionada==KeyEvent.VK_ENTER &&
            this.tbCIE10.getRowCount() != 0 &&
            this.tbCIE10.getSelectedRow() != -1){
            int fila = tbCIE10.getSelectedRow();

          CIE10.setVisible(false);

            txtCIE10.setText(String.valueOf(tbCIE10.getValueAt(fila, 0)));
            txtCIE10Desc.setText(String.valueOf(tbCIE10.getValueAt(fila, 1)));
            //btnmodificar.setEnabled(true);
            //btneliminar.setEnabled(true);
            String u=lblUsu.getText();
            lblUsu.setText(u);
            //txtFP.setEnabled(false);
           
        }

    }//GEN-LAST:event_tbCIE10KeyPressed

    private void btnBuscarCIE10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCIE10ActionPerformed
        try{
            String condicion =txtBuscarCIE10.getText().toString();

            DefaultTableModel tabla= new DefaultTableModel();

            tabla.addColumn("Código");
            tabla.addColumn("Descripción");
            cst=con.prepareCall("{call cie10_Buscar(?)}");
            cst.setString(1, condicion);
            r=cst.executeQuery();
            while (r.next()){
                Object dato[]=new  Object[2];
                for (int i=0; i<2; i++){
                    dato[i]=r.getString(i+1);

                }
                tabla.addRow(dato);
            }

            this.tbCIE10.setModel(tabla);

            formato_FP();
            txtBuscarCIE10.setText("");
            tbCIE10.getSelectionModel().setSelectionInterval(0, 0);
            tbCIE10.requestFocus();
            formatoCIE10();
        }catch (Exception e){}
    }//GEN-LAST:event_btnBuscarCIE10ActionPerformed

    private void txtBuscarCIE10KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarCIE10KeyPressed
        if(evt.getExtendedKeyCode()==KeyEvent.VK_DOWN){
            tbCIE10.getSelectionModel().setSelectionInterval(0, 0);
            tbCIE10.requestFocus();
        }
    }//GEN-LAST:event_txtBuscarCIE10KeyPressed

    private void txtBuscarCIE10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarCIE10KeyTyped
        char tecla= evt.getKeyChar();
        if(tecla==KeyEvent.VK_ENTER){
            btnBuscarCIE10.doClick();
        }
    }//GEN-LAST:event_txtBuscarCIE10KeyTyped

    public void calcula() {
        Calendar calendario = new GregorianCalendar();
        java.util.Date fechaHoraActual = new java.util.Date();


        calendario.setTime(fechaHoraActual);
        ampm = calendario.get(Calendar.AM_PM) == Calendar.AM ? "AM" : "PM";

        if (ampm.equals("PM")) {
            int h = calendario.get(Calendar.HOUR_OF_DAY) - 12;
            hora = h > 9 ? "" + h : "0" + h;
        } else {
            hora = calendario.get(Calendar.HOUR_OF_DAY) > 9 ? "" + calendario.get(Calendar.HOUR_OF_DAY) : "0" + calendario.get(Calendar.HOUR_OF_DAY);
        }
        minutos = calendario.get(Calendar.MINUTE) > 9 ? "" + calendario.get(Calendar.MINUTE) : "0" + calendario.get(Calendar.MINUTE);
        segundos = calendario.get(Calendar.SECOND) > 9 ? "" + calendario.get(Calendar.SECOND) : "0" + calendario.get(Calendar.SECOND);
    }   
    
    public void cargar_Forma_Pago(){
       
    try{
       DefaultTableModel tabla= new DefaultTableModel();
      
       tabla.addColumn("Código");
       tabla.addColumn("Forma de Pago");
       tabla.addColumn("Descripción");
 
       
       cst=con.prepareCall("SELECT cod_jerar_forma_pago, nom_forma_pago, descri_forma_pago FROM CAJA_JERARQUIA_FORMA_PAGO");
       r=cst.executeQuery();
       while (r.next()){
       Object dato[]=new  Object[3];
       for (int i=0; i<3; i++){
           dato[i]=r.getString(i+1);
       }
       tabla.addRow(dato);
       }
       this.tb_FP.setModel(tabla);
       formato_FP();
       
       }catch (Exception e){
       }
     }
    
    public void formato_FP(){
       tb_FP.getColumnModel().getColumn(0).setPreferredWidth(60);
       tb_FP.getColumnModel().getColumn(1).setPreferredWidth(150);
       tb_FP.getColumnModel().getColumn(2).setPreferredWidth(200);
    }
    
    public void cargar_CIE10(){
       
    try{
       DefaultTableModel tabla= new DefaultTableModel();
     
       tabla.addColumn("COD_ENF");
       tabla.addColumn("DESCRIPCION");
 
       
       cst=con.prepareCall("{call cie10_listar_c}");
       r=cst.executeQuery();
       while (r.next()){
       Object dato[]=new  Object[2];
       for (int i=0; i<2; i++){
           dato[i]=r.getString(i+1);
       }
       tabla.addRow(dato);
       }
       this.tbCIE10.setModel(tabla);
       formatoCIE10();
       
       }catch (Exception e){
       }
     }
    
    public void formatoCIE10(){
       tbCIE10.getColumnModel().getColumn(0).setPreferredWidth(100);
       tbCIE10.getColumnModel().getColumn(1).setPreferredWidth(500);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Asignar_CIE10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Asignar_CIE10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Asignar_CIE10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Asignar_CIE10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Asignar_CIE10().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog CIE10;
    private javax.swing.JButton btnBuscarCIE10;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btn_BuscarFP;
    public static javax.swing.JButton btnguardar;
    private javax.swing.JDialog forma_pago;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel jpanel;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblHora;
    public static javax.swing.JLabel lblUsu;
    private javax.swing.JTable tbCIE10;
    private javax.swing.JTable tb_FP;
    private javax.swing.JLabel titulo5;
    private javax.swing.JTextField txtBuscarCIE10;
    private javax.swing.JTextField txtBuscarFP;
    private javax.swing.JTextField txtCIE10;
    private javax.swing.JTextField txtCIE10Desc;
    private javax.swing.JTextField txtFP;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                Thread ct = Thread.currentThread();
        while (ct == h1) {
            calcula();
            lblHora.setText(hora + ":" + minutos + ":" + segundos + " " + ampm);
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
            }
        }
    }
}
