/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista.SALA_OPERACIONES;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import servicios.Conexion;

/**
 *
 * @author USUARIO
 */
public class frm_SALA_OPERACION_DROGAS_BUSCAR extends javax.swing.JFrame {
    Conexion conectar=new Conexion();
    Connection con;
    CallableStatement cst;
    ResultSet r;
    Statement st;
    
    /**
     * Creates new form frm_SALA_OPERACION_DROGAS_BUSCAR
     */
    public frm_SALA_OPERACION_DROGAS_BUSCAR() {
        initComponents();
        setLocationRelativeTo(null);//centrar el formulario
        this.getContentPane().setBackground(Color.WHITE);
        con=conectar.conectar();
        cargar_SDO_Drogas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBuscarDR = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_buscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_SDO_Drogas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        txtBuscarDR.setForeground(new java.awt.Color(0, 51, 51));
        txtBuscarDR.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtBuscarDRCaretUpdate(evt);
            }
        });
        txtBuscarDR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarDRActionPerformed(evt);
            }
        });
        txtBuscarDR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarDRKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarDRKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Búsqueda ");

        jLabel2.setText("Nombre:");

        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/Search-16.png"))); // NOI18N
        btn_buscar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_buscar.setContentAreaFilled(false);
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        tb_SDO_Drogas = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Disallow the editing of any cell
            }
        };
        tb_SDO_Drogas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_SDO_Drogas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tb_SDO_Drogas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tb_SDO_DrogasKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tb_SDO_Drogas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscarDR, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(txtBuscarDR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void cargar_SDO_Drogas(){
       
    try{
       DefaultTableModel tabla= new DefaultTableModel();
      
       tabla.addColumn("Codigo");
       tabla.addColumn("Descripción");
       tabla.addColumn("Unidad de Medida");
       tabla.addColumn("Stock");
 
       
       cst=con.prepareCall("{call SALA_OPERACION_DROGAS_LISTAR}");
       r=cst.executeQuery();
       while (r.next()){
       Object dato[]=new  Object[4];
       for (int i=0; i<4; i++){
           dato[i]=r.getString(i+1);
       }
       tabla.addRow(dato);
       }
       this.tb_SDO_Drogas.setModel(tabla);
       formato();
       
       }catch (Exception e){
       }
     }
    
    public void formato(){
       tb_SDO_Drogas.getColumnModel().getColumn(0).setPreferredWidth(100);
       tb_SDO_Drogas.getColumnModel().getColumn(1).setPreferredWidth(150);
       tb_SDO_Drogas.getColumnModel().getColumn(2).setPreferredWidth(120);
       tb_SDO_Drogas.getColumnModel().getColumn(3).setPreferredWidth(80);
    }
    
    private void txtBuscarDRCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtBuscarDRCaretUpdate

    }//GEN-LAST:event_txtBuscarDRCaretUpdate

    private void txtBuscarDRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarDRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarDRActionPerformed

    private void txtBuscarDRKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarDRKeyPressed
        if(evt.getExtendedKeyCode()==KeyEvent.VK_DOWN){
            tb_SDO_Drogas.getSelectionModel().setSelectionInterval(0, 0);
            tb_SDO_Drogas.requestFocus();
        }
    }//GEN-LAST:event_txtBuscarDRKeyPressed

    private void txtBuscarDRKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarDRKeyTyped
        char tecla= evt.getKeyChar();
        if(tecla==KeyEvent.VK_ENTER){
            btn_buscar.doClick();
        }
    }//GEN-LAST:event_txtBuscarDRKeyTyped

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed

        try{
            String SDO_Drogas =txtBuscarDR.getText().toString();

            DefaultTableModel tabla= new DefaultTableModel();

            tabla.addColumn("Codigo");
            tabla.addColumn("Descripcion");
            tabla.addColumn("Unidad de Medida");
            tabla.addColumn("Stock");
            cst=con.prepareCall("{call SALA_OPERACION_DROGAS_BUSCAR(?)}");
            cst.setString(1, SDO_Drogas);
            r=cst.executeQuery();
            while (r.next()){
                Object dato[]=new  Object[4];
                for (int i=0; i<4; i++){
                    dato[i]=r.getString(i+1);

                }
                tabla.addRow(dato);
            }

            this.tb_SDO_Drogas.setModel(tabla);

            formato();
            txtBuscarDR.setText("");
            tb_SDO_Drogas.getSelectionModel().setSelectionInterval(0, 0);
            tb_SDO_Drogas.requestFocus();
        }catch (Exception e){}

    }//GEN-LAST:event_btn_buscarActionPerformed

    private void tb_SDO_DrogasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tb_SDO_DrogasKeyPressed

        char teclaPresionada = evt.getKeyChar();

        if(teclaPresionada==KeyEvent.VK_ENTER &&
            this.tb_SDO_Drogas.getRowCount() == 0 &&
            this.tb_SDO_Drogas.getSelectedRow() == -1){

            JOptionPane.showMessageDialog(rootPane, "La tabla esta vacia");

        }else
        if(teclaPresionada==KeyEvent.VK_ENTER &&
            this.tb_SDO_Drogas.getRowCount() != 0 &&
            this.tb_SDO_Drogas.getSelectedRow() != -1){
            int fila = tb_SDO_Drogas.getSelectedRow();
            //frm_SALA_OPERACION_TIPO_ANESTESIA T = new frm_SALA_OPERACION_TIPO_ANESTESIA();
            //T.setVisible(true);
            dispose();

            frm_SALA_OPERACION_DROGAS.txtCodigo.setText(String.valueOf(tb_SDO_Drogas.getValueAt(fila, 0)));
            frm_SALA_OPERACION_DROGAS.txtDescripcion.setText(String.valueOf(tb_SDO_Drogas.getValueAt(fila, 1)));
            frm_SALA_OPERACION_DROGAS.txtUnidad.setText(String.valueOf(tb_SDO_Drogas.getValueAt(fila, 2)));
            frm_SALA_OPERACION_DROGAS.txtStock.setText(String.valueOf(tb_SDO_Drogas.getValueAt(fila, 3)));
            frm_SALA_OPERACION_DROGAS.btnmodificar.setEnabled(true);
            frm_SALA_OPERACION_DROGAS.btneliminar.setEnabled(true);
            String u=frm_SALA_OPERACION_DROGAS.lblUsu.getText();
            frm_SALA_OPERACION_DROGAS.lblUsu.setText(u);
            frm_SALA_OPERACION_DROGAS.txtDescripcion.setEnabled(false);
            frm_SALA_OPERACION_DROGAS.txtUnidad.setEnabled(false);
            frm_SALA_OPERACION_DROGAS.txtStock.setEnabled(false);
        }
    }//GEN-LAST:event_tb_SDO_DrogasKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_SALA_OPERACION_DROGAS_BUSCAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_SALA_OPERACION_DROGAS_BUSCAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_SALA_OPERACION_DROGAS_BUSCAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_SALA_OPERACION_DROGAS_BUSCAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_SALA_OPERACION_DROGAS_BUSCAR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btn_buscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tb_SDO_Drogas;
    public static javax.swing.JTextField txtBuscarDR;
    // End of variables declaration//GEN-END:variables
}
