/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.ALMACEN;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import modelos.ALMACEN.Producto_Insumos;
import modelos.FormatoTablaSIGA;
import modelos.LABORATORIO.LAB_Contenedor_Muestra;
import modelos.Usuario;
import servicios.Conexion;
import static vista.COSTOS.COSTOS_PRODUCTO_REFERENCIAL.tbProductoAlmacen;

/**
 *
 * @author PC-SISTEMA
 */
public class frm_Guia_Producto extends javax.swing.JFrame {
DefaultTableModel m2;
DefaultTableModel m3;
String hora, minutos, segundos, ampm;
    Calendar calendario;
    Thread h1;
    Conexion c=new Conexion();
    /**
     * Creates new form frm_Asig_Unidad_Medida
     */
    public frm_Guia_Producto() {
        initComponents();
         this.getContentPane().setBackground(Color.white); 
        //setIconImage(new ImageIcon(getClass().getResource("/imagenes/principal.png")).getImage());
        setLocationRelativeTo(null);//en el centro
        setResizable(false);//para que no funcione el boton maximizar
        cargarProducto();
        formatoProducto();
                    tbProductoAlmacen.getSelectionModel().setSelectionInterval(0, 0);
                    tbProductoAlmacen.requestFocus();
             
        
        //para no intercambiar columnas
        tbProductoAlmacen.getTableHeader().setReorderingAllowed(false);
    }

    
     public void cargarProducto(){
    try {
             String titulos[]={"Nº","Código","Nombre del Producto","Cantidad de Unidad de Medida","Unidad de Medida"};
            m2=new DefaultTableModel(null,titulos);
            JTable p=new JTable(m2);
            String fila[]=new String[6];
            
            Usuario obj=new Usuario();
            String consulta="exec ASIGNAR_UNIDAD_MEDIDA_LISTAR ?,?";
        
            PreparedStatement cmd = obj.getCn().prepareStatement(consulta);
            cmd.setString(1,"1");
            cmd.setString(2,"");
            ResultSet r= cmd.executeQuery();
            int c=1;
            
        while(r.next()){
            fila[0]=String.valueOf(c)+"º";
            fila[1]=r.getString(1);
            fila[2]=r.getString(2);
            fila[3]=r.getString(3);
            fila[4]=r.getString(4);
                m2.addRow(fila);
                c++;
            }
            tbProductoAlmacen.setModel(m2);
            TableRowSorter<TableModel> elQueOrdena=new TableRowSorter<TableModel>(m2);
            tbProductoAlmacen.setRowSorter(elQueOrdena);
            this.tbProductoAlmacen.setModel(m2);
    } catch (Exception e) {
    }
}
    public void formatoProducto(){
    tbProductoAlmacen.getColumnModel().getColumn(0).setPreferredWidth(35);
    tbProductoAlmacen.getColumnModel().getColumn(1).setPreferredWidth(140);
    tbProductoAlmacen.getColumnModel().getColumn(2).setPreferredWidth(360);
    tbProductoAlmacen.getColumnModel().getColumn(3).setPreferredWidth(140);
    tbProductoAlmacen.getColumnModel().getColumn(4).setPreferredWidth(140);
    
    tbProductoAlmacen.getColumnModel().getColumn(3).setMinWidth(0);
    tbProductoAlmacen.getColumnModel().getColumn(3).setMaxWidth(0);
    tbProductoAlmacen.getSelectionModel().setSelectionInterval(0, 0);
    tbProductoAlmacen.requestFocus();
}
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanel = new javax.swing.JPanel();
        titulo5 = new javax.swing.JLabel();
        lblUsu = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        tab = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txtCantidad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtProducto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbProductoAlmacen = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                if(colIndex==3){
                    return true;
                }else{
                    return false; //Disallow the editing of any cell
                }
            }};
            txtBuscar = new javax.swing.JTextField();
            btnBuscarProducto = new javax.swing.JButton();
            lblCodProducto = new javax.swing.JLabel();
            jPanel2 = new javax.swing.JPanel();
            jScrollPane3 = new javax.swing.JScrollPane();
            tbGuia = new javax.swing.JTable(){
                public boolean isCellEditable(int rowIndex, int colIndex){
                    if(colIndex==3){
                        return true;
                    }else{
                        return false; //Disallow the editing of any cell
                    }
                }};

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jpanel.setBackground(new java.awt.Color(126, 5, 46));

                titulo5.setBackground(new java.awt.Color(0, 102, 102));
                titulo5.setFont(new java.awt.Font("Segoe UI Semilight", 0, 36)); // NOI18N
                titulo5.setForeground(new java.awt.Color(255, 255, 255));
                titulo5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                titulo5.setText("Guía de Productos");
                titulo5.setToolTipText("");
                titulo5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

                lblUsu.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
                lblUsu.setForeground(new java.awt.Color(255, 255, 255));
                lblUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/User-32.png"))); // NOI18N
                lblUsu.setText("Usuario");

                btnNuevo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
                btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/Documento-32.png"))); // NOI18N
                btnNuevo.setMnemonic('N');
                btnNuevo.setToolTipText("Nuevo (Alt+N)");
                btnNuevo.setContentAreaFilled(false);
                btnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                btnNuevo.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnNuevoActionPerformed(evt);
                    }
                });

                btnguardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
                btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/Guardar-32.png"))); // NOI18N
                btnguardar.setMnemonic('G');
                btnguardar.setToolTipText("Guardar (Alt-G)");
                btnguardar.setContentAreaFilled(false);
                btnguardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                btnguardar.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnguardarActionPerformed(evt);
                    }
                });

                btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
                btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/Buscar-32.png"))); // NOI18N
                btnBuscar.setMnemonic('B');
                btnBuscar.setToolTipText("Buscar (Alt+B)");
                btnBuscar.setContentAreaFilled(false);
                btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                btnBuscar.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnBuscarActionPerformed(evt);
                    }
                });

                javax.swing.GroupLayout jpanelLayout = new javax.swing.GroupLayout(jpanel);
                jpanel.setLayout(jpanelLayout);
                jpanelLayout.setHorizontalGroup(
                    jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelLayout.createSequentialGroup()
                        .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanelLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(titulo5))
                            .addGroup(jpanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                );
                jpanelLayout.setVerticalGroup(
                    jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelLayout.createSequentialGroup()
                        .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(titulo5)
                            .addComponent(lblUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar)
                            .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                );

                tab.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

                jPanel1.setBackground(new java.awt.Color(255, 255, 255));

                txtCantidad.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
                txtCantidad.setForeground(new java.awt.Color(0, 51, 51));
                txtCantidad.setSelectionColor(new java.awt.Color(126, 5, 46));
                txtCantidad.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        txtCantidadActionPerformed(evt);
                    }
                });
                txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
                    public void keyPressed(java.awt.event.KeyEvent evt) {
                        txtCantidadKeyPressed(evt);
                    }
                    public void keyTyped(java.awt.event.KeyEvent evt) {
                        txtCantidadKeyTyped(evt);
                    }
                });

                jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
                jLabel1.setText("Cantidad");

                txtProducto.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
                txtProducto.setForeground(new java.awt.Color(0, 51, 51));
                txtProducto.setSelectionColor(new java.awt.Color(126, 5, 46));
                txtProducto.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        txtProductoActionPerformed(evt);
                    }
                });
                txtProducto.addKeyListener(new java.awt.event.KeyAdapter() {
                    public void keyPressed(java.awt.event.KeyEvent evt) {
                        txtProductoKeyPressed(evt);
                    }
                    public void keyTyped(java.awt.event.KeyEvent evt) {
                        txtProductoKeyTyped(evt);
                    }
                });

                jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
                jLabel2.setText("Producto");

                tbProductoAlmacen.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
                tbProductoAlmacen.setModel(new javax.swing.table.DefaultTableModel(
                    new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                    },
                    new String [] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                    }
                ) {
                    boolean[] canEdit = new boolean [] {
                        false, true, true, true
                    };

                    public boolean isCellEditable(int rowIndex, int columnIndex) {
                        return canEdit [columnIndex];
                    }
                });
                tbProductoAlmacen.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
                tbProductoAlmacen.setRowHeight(25);
                tbProductoAlmacen.setSelectionBackground(new java.awt.Color(126, 5, 46));
                tbProductoAlmacen.setSelectionForeground(new java.awt.Color(0, 0, 0));
                tbProductoAlmacen.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        tbProductoAlmacenMouseClicked(evt);
                    }
                });
                tbProductoAlmacen.addKeyListener(new java.awt.event.KeyAdapter() {
                    public void keyPressed(java.awt.event.KeyEvent evt) {
                        tbProductoAlmacenKeyPressed(evt);
                    }
                    public void keyTyped(java.awt.event.KeyEvent evt) {
                        tbProductoAlmacenKeyTyped(evt);
                    }
                });
                jScrollPane2.setViewportView(tbProductoAlmacen);
                if (tbProductoAlmacen.getColumnModel().getColumnCount() > 0) {
                    tbProductoAlmacen.getColumnModel().getColumn(0).setResizable(false);
                    tbProductoAlmacen.getColumnModel().getColumn(1).setResizable(false);
                    tbProductoAlmacen.getColumnModel().getColumn(2).setResizable(false);
                    tbProductoAlmacen.getColumnModel().getColumn(3).setResizable(false);
                }

                txtBuscar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
                txtBuscar.setForeground(new java.awt.Color(0, 51, 51));
                txtBuscar.setSelectionColor(new java.awt.Color(126, 5, 46));
                txtBuscar.addCaretListener(new javax.swing.event.CaretListener() {
                    public void caretUpdate(javax.swing.event.CaretEvent evt) {
                        txtBuscarCaretUpdate(evt);
                    }
                });
                txtBuscar.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        txtBuscarActionPerformed(evt);
                    }
                });
                txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
                    public void keyPressed(java.awt.event.KeyEvent evt) {
                        txtBuscarKeyPressed(evt);
                    }
                    public void keyTyped(java.awt.event.KeyEvent evt) {
                        txtBuscarKeyTyped(evt);
                    }
                });

                btnBuscarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/Búsqueda-25.png"))); // NOI18N
                btnBuscarProducto.setBorder(null);
                btnBuscarProducto.setContentAreaFilled(false);
                btnBuscarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                btnBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnBuscarProductoActionPerformed(evt);
                    }
                });

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCantidad))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCodProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarProducto)
                                .addGap(142, 142, 142))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(15, Short.MAX_VALUE))))
                );
                jPanel1Layout.setVerticalGroup(
                    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCodProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnBuscarProducto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                tab.addTab("tab1", jPanel1);

                jPanel2.setBackground(new java.awt.Color(255, 255, 255));

                tbGuia.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
                tbGuia.setModel(new javax.swing.table.DefaultTableModel(
                    new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                    },
                    new String [] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                    }
                ) {
                    boolean[] canEdit = new boolean [] {
                        false, true, true, true
                    };

                    public boolean isCellEditable(int rowIndex, int columnIndex) {
                        return canEdit [columnIndex];
                    }
                });
                tbGuia.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
                tbGuia.setRowHeight(25);
                tbGuia.setSelectionBackground(new java.awt.Color(126, 5, 46));
                tbGuia.setSelectionForeground(new java.awt.Color(0, 0, 0));
                tbGuia.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        tbGuiaMouseClicked(evt);
                    }
                });
                tbGuia.addKeyListener(new java.awt.event.KeyAdapter() {
                    public void keyPressed(java.awt.event.KeyEvent evt) {
                        tbGuiaKeyPressed(evt);
                    }
                    public void keyTyped(java.awt.event.KeyEvent evt) {
                        tbGuiaKeyTyped(evt);
                    }
                });
                jScrollPane3.setViewportView(tbGuia);
                if (tbGuia.getColumnModel().getColumnCount() > 0) {
                    tbGuia.getColumnModel().getColumn(0).setResizable(false);
                    tbGuia.getColumnModel().getColumn(1).setResizable(false);
                    tbGuia.getColumnModel().getColumn(2).setResizable(false);
                    tbGuia.getColumnModel().getColumn(3).setResizable(false);
                }

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                    jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(21, Short.MAX_VALUE))
                );
                jPanel2Layout.setVerticalGroup(
                    jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(38, Short.MAX_VALUE))
                );

                tab.addTab("tab2", jPanel2);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tab, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tab)
                        .addGap(13, 13, 13))
                );

                pack();
            }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void txtBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyPressed
        // TODO add your handling code here:
        char tecla= evt.getKeyChar();
        if(tecla==KeyEvent.VK_ENTER){
            btnBuscarProducto.doClick();
        }
    }//GEN-LAST:event_txtBuscarKeyPressed

    private void txtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyTyped

    }//GEN-LAST:event_txtBuscarKeyTyped

    private void btnBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProductoActionPerformed
        // TODO add your handling code here:
        String consulta="";
        try {
            tbProductoAlmacen.setModel(new DefaultTableModel());

            String titulos[]={"Nº","Código","Nombre del Producto","Cantidad de Unidad de Medida","Unidad de Medida"};
            m3=new DefaultTableModel(null,titulos);
            JTable p=new JTable(m3);
            String fila[]=new String[6];
            
            Usuario obj=new Usuario();
            consulta="exec ASIGNAR_UNIDAD_MEDIDA_LISTAR ?,?";
        
            PreparedStatement cmd = obj.getCn().prepareStatement(consulta);
            cmd.setString(1,"2");
            cmd.setString(2,txtBuscar.getText());
            
            ResultSet r= cmd.executeQuery();
            int c=1;
            while(r.next()){
                fila[0]=String.valueOf(c)+"º";
                fila[1]=r.getString(1);
                fila[2]=r.getString(2);
                fila[3]=r.getString(3);
                fila[4]=r.getString(4);
                m3.addRow(fila);
                c++;
            }
            tbProductoAlmacen.setModel(m3);
            TableRowSorter<TableModel> elQueOrdena=new TableRowSorter<TableModel>(m3);
            tbProductoAlmacen.setRowSorter(elQueOrdena);
            this.tbProductoAlmacen.setModel(m3);
            formatoProducto();
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarProductoActionPerformed

    private void tbProductoAlmacenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbProductoAlmacenKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tbProductoAlmacenKeyTyped

    private void tbProductoAlmacenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbProductoAlmacenKeyPressed
   char tecla= evt.getKeyChar();
                if(tecla==KeyEvent.VK_ENTER){
                     try{
                        int filaselec=tbProductoAlmacen.getSelectedRow();
                        
                        lblCodProducto.setText(tbProductoAlmacen.getValueAt(filaselec, 1).toString());
                        txtProducto.setText(tbProductoAlmacen.getValueAt(filaselec, 2).toString());
                     
                    }
                    catch(Exception ex)
                    {
                        System.out.println("Error: " + ex.getMessage());
                    }
                }
    }//GEN-LAST:event_tbProductoAlmacenKeyPressed

    private void tbProductoAlmacenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbProductoAlmacenMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbProductoAlmacenMouseClicked

    private void txtProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductoActionPerformed

    private void txtProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProductoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductoKeyPressed

    private void txtProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProductoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductoKeyTyped

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void txtCantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadKeyPressed

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadKeyTyped

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed

        enableDatos(true);
        limpiar();

    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
//        ImageIcon i=new ImageIcon(this.getClass().getResource("/imagenes/iconos/guardar16x16.png"));
//        LAB_Analisis_Examen me=new  LAB_Analisis_Examen();
//        LAB_Analisis_Examen me1=new LAB_Analisis_Examen();
//        LAB_Analisis_Examen me2=new LAB_Analisis_Examen();
//        try{
//            if(txtGuarModif.getText().equalsIgnoreCase("G")){
//                if(txtClasificacion.getText().equalsIgnoreCase("")||txtCodClasificacion.getText().equalsIgnoreCase("")){
//                    JOptionPane.showMessageDialog(rootPane, "Seleccione una Clasificación del Examen");
//                }  else if(txtCodNomen.getText().equalsIgnoreCase("")||txtCodigoCPT.getText().equalsIgnoreCase("")
//                    ||txtNomen.getText().equalsIgnoreCase("")){
//                    JOptionPane.showMessageDialog(rootPane, "Seleccione un Código CPT");
//                }
//                else if(txtNombreExamen.getText().equalsIgnoreCase("")||txtAbrev.getText().equalsIgnoreCase("")||
//                    cbxTipoProc.getSelectedIndex()==0 || cbxRestric.getSelectedIndex()==0 ){
//                    JOptionPane.showMessageDialog(rootPane, "Ingrese todos los campos");
//                }  else if(tb_Muestras.getRowCount()==0){
//                    JOptionPane.showMessageDialog(rootPane, "Seleccione una Muestra");
//                }
//                else if(me1.LAB_Analisis_Examen_ver(txtCodClasificacion.getText(),txtCodNomen.getText())>0){
//                    JOptionPane.showMessageDialog(rootPane, "El Registro ya ha sido ingresado\nIntente nuevamente");
//
//                    txtClasificacion.setText("");
//                    txtClasificacion.requestFocus();
//                }
//                else{
//                    int guardar = JOptionPane.showConfirmDialog(this, "¿Está seguro que desea GUARDAR los datos?",
//                        "Atención", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,i);
//                    if(guardar == 0 ){
//                        LAB_Analisis_Examen meGuardar = new LAB_Analisis_Examen();
//                        meGuardar.setCod_exa_ana(txtCodigo.getText());
//                        meGuardar.setCod_clasi_exa(txtCodClasificacion.getText());
//                        meGuardar.setCod_nomen_caja(txtCodNomen.getText());
//                        meGuardar.setNombre_ana_exa(txtNombreExamen.getText());
//                        meGuardar.setAbrev_ana_exa(txtAbrev.getText());
//                        meGuardar.setTiempo_hora(Integer.parseInt(txtTiempoHora.getText()));
//                        meGuardar.setTiempo_min(Integer.parseInt(txtTiempoMin.getText()));
//                        meGuardar.setTipo_procesamiento(cbxTipoProc.getSelectedItem().toString());
//                        meGuardar.setRestriccion_analisis(cbxRestric.getSelectedItem().toString());
//                        meGuardar.setExplicacion_met_proce(txtExplicacion.getText());
//                        if(chActivo.isSelected()){
//                            meGuardar.setEstado_detalle("A");
//                        }else{
//                            meGuardar.setEstado_detalle("D");
//                        }
//                        meGuardar.setObservacion_ana_exa(txtObservacion.getText());
//                        meGuardar.setNom_usu(lblUsu.getText());
//
//                        if(meGuardar.LAB_Analisis_Examen_guardar()){
//                            JOptionPane.showMessageDialog(null, "Datos Guardados");
//                            guardarDetalle();
//                            limpiar();
//                            enableDatos();
//                            txtGuarModif.setText("G");
//                        }
//                        else{
//                            JOptionPane.showMessageDialog(this, "El Registro ya ha sido ingresado\nIntente nuevamente");
//                        }}
//                    }}else{
//                        if(txtClasificacion.getText().equalsIgnoreCase("")||txtCodClasificacion.getText().equalsIgnoreCase("")){
//                            JOptionPane.showMessageDialog(rootPane, "Busque una Unidad Orgánica");
//                        }  else if(tb_Muestras.getRowCount()==0){
//                            JOptionPane.showMessageDialog(rootPane, "Seleccione una Muestra");
//                        }
//                        else{
//                            int modificar = JOptionPane.showConfirmDialog(this, "¿Está seguro que desea MODIFICAR los datos?",
//                                "Atención", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,i);
//                            if(modificar == 0 ){
//                                LAB_Analisis_Examen meModif = new LAB_Analisis_Examen();
//                                meModif.setCod_exa_ana(txtCodigo.getText());
//                                meModif.setCod_clasi_exa(txtCodClasificacion.getText());
//                                meModif.setCod_nomen_caja(txtCodNomen.getText());
//                                meModif.setNombre_ana_exa(txtNombreExamen.getText());
//                                meModif.setAbrev_ana_exa(txtAbrev.getText());
//                                meModif.setTiempo_hora(Integer.parseInt(txtTiempoHora.getText()));
//                                meModif.setTiempo_min(Integer.parseInt(txtTiempoMin.getText()));
//                                meModif.setTipo_procesamiento(cbxTipoProc.getSelectedItem().toString());
//                                meModif.setRestriccion_analisis(cbxRestric.getSelectedItem().toString());
//                                meModif.setExplicacion_met_proce(txtExplicacion.getText());
//                                if(chActivo.isSelected()){
//                                    meModif.setEstado_detalle("A");
//                                }else{
//                                    meModif.setEstado_detalle("D");
//                                }
//                                meModif.setObservacion_ana_exa(txtObservacion.getText());
//                                meModif.setNom_usu(lblUsu.getText());
//
//                                LAB_Analisis_Detalle rdeliminar=new LAB_Analisis_Detalle();
//                                rdeliminar.setCod_exa_ana(txtCodigo.getText());
//
//                                if(meModif.LAB_Analisis_Examen_modificar()&& rdeliminar.LAB_Analisis_Detalle_eliminar()){
//                                    JOptionPane.showMessageDialog(this, "Datos Modificados");
//                                    guardarDetalle();
//                                    limpiar();
//                                    enableDatos();
//                                    txtGuarModif.setText("G");
//                                }
//                                else{
//                                    JOptionPane.showMessageDialog(this, "El Registro ya ha sido ingresado\nIntente nuevamente");
//
//                                }}
//                            }}}catch(Exception e) {
//                                JOptionPane.showMessageDialog(this, "Ingrese todos los campos");
//
//                            }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed


    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tbGuiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbGuiaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbGuiaMouseClicked

    private void tbGuiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbGuiaKeyPressed
      tab.setSelectedIndex(1);
    }//GEN-LAST:event_tbGuiaKeyPressed

    private void tbGuiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbGuiaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tbGuiaKeyTyped

    private void txtBuscarCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtBuscarCaretUpdate
      btnBuscarProducto.doClick();
    }//GEN-LAST:event_txtBuscarCaretUpdate
 public void enableDatos(boolean op){
    btnNuevo.setVisible(op);
    txtProducto.setVisible(op);
    txtCantidad.setVisible(op);
}
    public void limpiar(){
    lblCodProducto.setText("");
    txtProducto.setText("");
    txtCantidad.setText("");
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Guia_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Guia_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Guia_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Guia_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Guia_Producto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarProducto;
    private javax.swing.JButton btnNuevo;
    public static javax.swing.JButton btnguardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel jpanel;
    private javax.swing.JLabel lblCodProducto;
    public static javax.swing.JLabel lblUsu;
    private javax.swing.JTabbedPane tab;
    public static javax.swing.JTable tbGuia;
    public static javax.swing.JTable tbProductoAlmacen;
    private javax.swing.JLabel titulo5;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtProducto;
    // End of variables declaration//GEN-END:variables
}
