/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.PERSONAL;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author PC02
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() throws ParseException {
        initComponents();
        this.setLocationRelativeTo(null);
//        DateFormat hora1 = new SimpleDateFormat("HH:mm:ss"); 
//        DateFormat hora2 = new SimpleDateFormat("HH:mm:ss"); 
//        
//        String s = "08:00:00";
//        String s1 = "12:30:00";
//        
//        String [] ss = s.split(":");
//        String [] sss = s1.split(":");
//        
//        String part1 = ss[0];
//        String part2 = sss[0];
////        
////        long lantes = Long.parseLong(part1);
////        long lahora = Long.parseLong(part2);
//        long diferencia = (Long.parseLong(part2) - Long.parseLong(part1)); 
//        System.out.println(new java.text.SimpleDateFormat( "HH:mm:ss" ).format( new Date(diferencia) ));
        
        
        ///////////////////////////////////////
        
        
//        long tiempoInicial=100000;
//        long tiempoFinal=123000; 
//        long resta=tiempoFinal - tiempoInicial;
//        //el metodo getTime te devuelve en mili segundos para saberlo en mins debes hacer
//        resta=resta /(1000*60);
//        System.out.println("diferencia" + resta);
        
        ////////////////////////////////
        
//        Date hora1 = new SimpleDateFormat().parse("19/05/2006 05:00:00"); 
//        Date hora2 = new SimpleDateFormat().parse("19/05/2006 22:30:30"); 
//        long lantes = hora1.getTime(); 
//        long lahora = hora2.getTime(); 
//        System.out.println((lahora - lantes)/3600000); 
        
        
        ////////////////////////////////
        
//        Date hora1 = new SimpleDateFormat().parse("19/05/2006 05:00:00"); 
//        Date hora2 = new SimpleDateFormat().parse("19/05/2006 05:00:00"); 
//        long lantes = hora1.getTime(); 
//        long lahora = hora2.getTime(); 
//        long diferencia = (lahora - lantes); 
//        System.out.println(new java.text.SimpleDateFormat( "HH:mm:ss" ).format( new Date(diferencia) ));
//        
//        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fecha1 = new javax.swing.JComboBox();
        fecha2 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fecha1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar...", "08:20:00", "09:30:00", "10:00:00", "10:30:00", "11:50:00", "11:10:00", "13:20:00", "14:10:00", "15:59:00", "16:01:00", "17:01:00", "18:01:00", "17:02:00", "18:05:00", "18:37:00", "19:01:00", "19:49:00", "20:16:00", "21:30:00", "22:10:00", "22:50:00", "23:15:00", "23:59:00", "18:46:00" }));
        fecha1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                fecha1ItemStateChanged(evt);
            }
        });
        fecha1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                fecha1PropertyChange(evt);
            }
        });

        fecha2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar...", "08:20:00", "09:30:00", "10:00:00", "10:30:00", "11:50:00", "11:10:00", "13:20:00", "14:10:00", "15:59:00", "16:01:00", "17:01:00", "18:01:00", "17:02:00", "18:05:00", "18:37:00", "19:01:00", "19:49:00", "20:16:00", "21:30:00", "22:10:00", "22:50:00", "23:15:00", "23:59:00", "22:00:00", "18:30:00", "18:31:00", "00:00:00", "00:48:00", "00:57:00", "01:46:00", "03:00:00", "08:50:00" }));
        fecha2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                fecha2ItemStateChanged(evt);
            }
        });
        fecha2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                fecha2PropertyChange(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fecha2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(fecha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(194, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fecha1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_fecha1PropertyChange
        
        
    }//GEN-LAST:event_fecha1PropertyChange

    private void fecha1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_fecha1ItemStateChanged

        
    }//GEN-LAST:event_fecha1ItemStateChanged

    private void fecha2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_fecha2ItemStateChanged
        String h = fecha1.getSelectedItem().toString();
        String h2 = fecha2.getSelectedItem().toString();
        
        int a = Integer.parseInt(h.substring(0, 2));
        int b = Integer.parseInt(h.substring(3, 5));
        int c = Integer.parseInt(h.substring(6, 8));
        
        int a1 = Integer.parseInt(h2.substring(0, 2));
        int b1 = Integer.parseInt(h2.substring(3, 5));
        int c1 = Integer.parseInt(h2.substring(6, 8));
        
        int hora =0, minuto=0, segundo =0;
        
        if(a < a1 && b < b1){
            hora = a1 - a;
            minuto = b1 - b;
        }
        if(a == a1 && b < b1){
            hora = 00;
            minuto = b1 - b;
        }
        if(a < a1 && b == b1){
            hora = a1 - a;
            minuto = 00;
        }
        if(a < a1 && b > b1){
            hora = (a1 - a) - 1;
            int m=0;
            m = 60 - b;
            minuto = m + b1;
        }
        
        //// PASAR DIA
        if(a1==00 && b1==00){
            hora = (24 - a) -1;
            minuto = 60 - b;
        }
        if(a1==00 && b1 > 0){
            int q=0, w=0, q1=0,w1=0;
            q = (24 - a) -1;
            w = 60 - b;
            q1 = 00;
            w1 = b1;
            hora = q + q1 ;
            minuto = w + w1;
            
            if(minuto > 60){
            hora = hora + 1;
            minuto = minuto - 60;
        }
        }
        
        String horaf = "", minutof ="";
        if(hora < 10){
            horaf = ("0" + hora);
        }else{
            horaf = String.valueOf(hora);
        }
        if(minuto < 10){
            minutof = ("0" + minuto);
        }else{
            minutof = String.valueOf(minuto);
        }

        System.out.println("hora: " + horaf + " " + minutof + " " + segundo);
    }//GEN-LAST:event_fecha2ItemStateChanged

    private void fecha2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_fecha2PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_fecha2PropertyChange

    
    public void hora(){
//        try {
//            
//       
//        Calendar calendario = new GregorianCalendar();
//        
//        int dia = fecha_inicio.getCalendar().get(Calendar.HOUR_OF_DAY);
//        int mes = fecha_inicio.getCalendar().get(Calendar.MINUTE);
//        int anio = fecha_inicio.getCalendar().get(Calendar.SECOND);
//        
//        
////        long s = Long.parseLong(dia+"");
////        long s1 = Long.parseLong(mes+"");
////        long s2 = Long.parseLong(anio+"");
////        
////        int hora =calendario.get(Calendar.HOUR_OF_DAY);
////        int minutos = calendario.get(Calendar.MINUTE);
////        int segundos = calendario.get(Calendar.SECOND);
////        
//        System.out.println(dia);
//        System.out.println(mes);
//        System.out.println(anio);
//         } catch (Exception e) {
//             System.out.println("error" + e.getMessage());
//        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new NewJFrame().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox fecha1;
    private javax.swing.JComboBox fecha2;
    // End of variables declaration//GEN-END:variables
}
