/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.hospitalizacion;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import modelos.Caja.Caja_Preventa;
import modelos.hospitalizacion.HospitalizacionPapeletas;
import servicios.Conexion;

/**
 *
 * @author Yamila
 */
public class FrmHospitalizacionListarCajaPreventa extends javax.swing.JFrame {

    DefaultTableModel m;
    Connection conexion=null;
    Conexion c = new Conexion();
    ResultSet r;
    HospitalizacionPapeletas hosP = new HospitalizacionPapeletas();
    public FrmHospitalizacionListarCajaPreventa() {
        initComponents();
        this.setLocationRelativeTo(null);//en el centro
        this.setResizable(false);//deshabilita boton maximizar
        this.getContentPane().setBackground(Color.WHITE);//color blanco del formulario
        conexion = c.conectar();
        //BOTON CERRAR
        getRootPane().getInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW).put(
        javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0), "Cancel");
        // BOTON ESCAPE (ESC)
        getRootPane().getActionMap().put("Cancel", new javax.swing.AbstractAction(){
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e)
            {
                dispose();
            }
        });
        hosP.listarPapeleta("P", txtBuscarr.getText(), tbListarPapeleta,"C");
        cerrar();
        JTableHeader th; 
        th = tbListarPapeleta.getTableHeader(); 
        Font fuente = new Font("Segoe UI Light", Font.CENTER_BASELINE, 14); 
        th.setFont(fuente); 
    }
    
    public void cerrar (){
        try {
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter() {
                public void windowClosing(WindowEvent e){
                    dispose();
                }
});
            this.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        mnuCjPreventa = new javax.swing.JPopupMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuEliminar = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuFormatoHC = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenu1 = new javax.swing.JMenu();
        mnuForHC = new javax.swing.JMenuItem();
        mnuExClinico = new javax.swing.JMenuItem();
        mnuCtrlVital = new javax.swing.JMenuItem();
        mnuHjEvolucion = new javax.swing.JMenuItem();
        mnuNotEnfermeria = new javax.swing.JMenuItem();
        mnuForInterconsulta = new javax.swing.JMenuItem();
        mnuExComplemen = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbListarPapeleta = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        titulo5 = new javax.swing.JLabel();
        lblUsuUsuario = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        txtBuscarr = new javax.swing.JTextField();
        rbtP = new javax.swing.JRadioButton();
        rbtH = new javax.swing.JRadioButton();

        mnuCjPreventa.setBackground(new java.awt.Color(255, 255, 255));
        mnuCjPreventa.add(jSeparator1);

        mnuEliminar.setFont(new java.awt.Font("Segoe UI Light", 1, 15)); // NOI18N
        mnuEliminar.setText("Eliminar");
        mnuEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEliminarActionPerformed(evt);
            }
        });
        mnuCjPreventa.add(mnuEliminar);
        mnuCjPreventa.add(jSeparator2);

        jMenuItem1.setFont(new java.awt.Font("Segoe UI Light", 1, 15)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/opciones.png"))); // NOI18N
        jMenuItem1.setText("Opciones");
        mnuFormatoHC.add(jMenuItem1);
        mnuFormatoHC.add(jSeparator3);

        jMenu1.setText("Formato de Historia Clínica");
        jMenu1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N

        mnuForHC.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        mnuForHC.setText("Formato H.C. Hospitalaria");
        jMenu1.add(mnuForHC);

        mnuExClinico.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        mnuExClinico.setText("Examen Clínico");
        jMenu1.add(mnuExClinico);

        mnuCtrlVital.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        mnuCtrlVital.setText("Controles Vitales");
        jMenu1.add(mnuCtrlVital);

        mnuHjEvolucion.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        mnuHjEvolucion.setText("Hoja de Evolución");
        jMenu1.add(mnuHjEvolucion);

        mnuNotEnfermeria.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        mnuNotEnfermeria.setText("Notas de Enfermeria");
        jMenu1.add(mnuNotEnfermeria);

        mnuForInterconsulta.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        mnuForInterconsulta.setText("Formato de Interconsulta");
        jMenu1.add(mnuForInterconsulta);

        mnuExComplemen.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        mnuExComplemen.setText("Examenes Complementarios");
        jMenu1.add(mnuExComplemen);

        mnuFormatoHC.add(jMenu1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 720));
        getContentPane().setLayout(null);

        jScrollPane1.setBorder(null);

        tbListarPapeleta = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tbListarPapeleta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbListarPapeleta.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tbListarPapeleta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbListarPapeleta.setSelectionBackground(new java.awt.Color(235, 105, 57));
        tbListarPapeleta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbListarPapeletaMouseReleased(evt);
            }
        });
        tbListarPapeleta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbListarPapeletaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbListarPapeleta);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 110, 1300, 530);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1300, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 650, 1300, 35);

        jPanel8.setBackground(new java.awt.Color(235, 105, 57));
        jPanel8.setPreferredSize(new java.awt.Dimension(500, 65));
        jPanel8.setLayout(null);

        titulo5.setBackground(new java.awt.Color(153, 0, 51));
        titulo5.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        titulo5.setForeground(new java.awt.Color(255, 255, 255));
        titulo5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titulo5.setText("Papeleta de Hospitalización");
        titulo5.setToolTipText("");
        titulo5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel8.add(titulo5);
        titulo5.setBounds(10, 10, 400, 41);

        lblUsuUsuario.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        lblUsuUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuUsuario.setText("Silvana");
        jPanel8.add(lblUsuUsuario);
        lblUsuUsuario.setBounds(1190, 20, 85, 20);

        jLabel19.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/User-32.png"))); // NOI18N
        jPanel8.add(jLabel19);
        jLabel19.setBounds(1150, 20, 32, 24);

        btnBuscar.setBackground(new java.awt.Color(204, 204, 204));
        btnBuscar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/Buscar-32.png"))); // NOI18N
        btnBuscar.setToolTipText("Buscar (Alt + F3)");
        btnBuscar.setContentAreaFilled(false);
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.setFocusable(false);
        btnBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel8.add(btnBuscar);
        btnBuscar.setBounds(280, 70, 38, 32);

        txtBuscarr.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        txtBuscarr.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtBuscarrCaretUpdate(evt);
            }
        });
        txtBuscarr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarrKeyPressed(evt);
            }
        });
        jPanel8.add(txtBuscarr);
        txtBuscarr.setBounds(10, 70, 270, 30);

        rbtP.setBackground(new java.awt.Color(235, 105, 57));
        buttonGroup1.add(rbtP);
        rbtP.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        rbtP.setForeground(new java.awt.Color(255, 255, 255));
        rbtP.setSelected(true);
        rbtP.setText("Pendientes");
        rbtP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtPActionPerformed(evt);
            }
        });
        jPanel8.add(rbtP);
        rbtP.setBounds(350, 70, 120, 29);

        rbtH.setBackground(new java.awt.Color(235, 105, 57));
        buttonGroup1.add(rbtH);
        rbtH.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        rbtH.setForeground(new java.awt.Color(255, 255, 255));
        rbtH.setText("Hospitalizados");
        rbtH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtHActionPerformed(evt);
            }
        });
        jPanel8.add(rbtH);
        rbtH.setBounds(480, 70, 150, 29);

        getContentPane().add(jPanel8);
        jPanel8.setBounds(0, 0, 1300, 120);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void rbtPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtPActionPerformed
        hosP.listarPapeleta("P", txtBuscarr.getText(), tbListarPapeleta,"C");
    }//GEN-LAST:event_rbtPActionPerformed

    private void txtBuscarrCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtBuscarrCaretUpdate
        if(rbtP.isSelected())
            hosP.listarPapeleta("P", txtBuscarr.getText(), tbListarPapeleta,"C");
        else
            hosP.listarPapeleta("H", txtBuscarr.getText(), tbListarPapeleta,"C");
    }//GEN-LAST:event_txtBuscarrCaretUpdate

    private void rbtHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtHActionPerformed
        hosP.listarPapeleta("H", txtBuscarr.getText(), tbListarPapeleta,"C");
    }//GEN-LAST:event_rbtHActionPerformed

    private void txtBuscarrKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarrKeyPressed
        if(evt.getExtendedKeyCode()==KeyEvent.VK_DOWN){
            tbListarPapeleta.getSelectionModel().setSelectionInterval(0,0);
            tbListarPapeleta.requestFocus();
        }
    }//GEN-LAST:event_txtBuscarrKeyPressed

    private void tbListarPapeletaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbListarPapeletaKeyPressed
        if(evt.getExtendedKeyCode()==KeyEvent.VK_UP && tbListarPapeleta.getSelectedRow()==0){
            tbListarPapeleta.getSelectionModel().setSelectionInterval(0,0);
            txtBuscarr.requestFocus();
        }
    }//GEN-LAST:event_tbListarPapeletaKeyPressed

    private void tbListarPapeletaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbListarPapeletaMouseReleased
       if(rbtP.isSelected()){
            int fila = tbListarPapeleta.getSelectedRow();
            if(fila == -1)
                JOptionPane.showMessageDialog(this, "Seleccione una fila");
            else{
                if(evt.isPopupTrigger()){
                    mnuCjPreventa.show(evt.getComponent(),evt.getX(),evt.getY());
                }
            }
        }
       if(rbtH.isSelected()){
            int fila = tbListarPapeleta.getSelectedRow();
            if(fila == -1)
                JOptionPane.showMessageDialog(this, "Seleccione una fila");
            else{
                if(evt.isPopupTrigger()){
                    mnuFormatoHC.show(evt.getComponent(),evt.getX(),evt.getY());
                }
            }
       }
    }//GEN-LAST:event_tbListarPapeletaMouseReleased

    private void mnuEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEliminarActionPerformed
        int fila = tbListarPapeleta.getSelectedRow();
        ImageIcon i=new ImageIcon(this.getClass().getResource("/imagenes/iconos/alerta32x32.png"));
        int guardar = JOptionPane.showConfirmDialog(this, "¿Está seguro que desea ELIMINAR los datos?",
                      "Atención", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,i);
        int id_preventa = Integer.parseInt(String.valueOf(tbListarPapeleta.getValueAt(fila, 0)));
        Caja_Preventa cp = new Caja_Preventa();
        cp.setId_preventa(id_preventa);
        if(guardar==0){
            if(cp.mantenimientoCajaPreventaHospitalizacion("E")){
                JOptionPane.showMessageDialog(this, "Registro eliminado", "Mensaje", 0, i);
            }
        }
    }//GEN-LAST:event_mnuEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmHospitalizacionListarCajaPreventa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmHospitalizacionListarCajaPreventa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmHospitalizacionListarCajaPreventa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmHospitalizacionListarCajaPreventa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmHospitalizacionListarCajaPreventa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    public static javax.swing.JLabel lblUsuUsuario;
    private javax.swing.JPopupMenu mnuCjPreventa;
    private javax.swing.JMenuItem mnuCtrlVital;
    private javax.swing.JMenuItem mnuEliminar;
    private javax.swing.JMenuItem mnuExClinico;
    private javax.swing.JMenuItem mnuExComplemen;
    private javax.swing.JMenuItem mnuForHC;
    private javax.swing.JMenuItem mnuForInterconsulta;
    private javax.swing.JPopupMenu mnuFormatoHC;
    private javax.swing.JMenuItem mnuHjEvolucion;
    private javax.swing.JMenuItem mnuNotEnfermeria;
    public static javax.swing.JRadioButton rbtH;
    public static javax.swing.JRadioButton rbtP;
    public static javax.swing.JTable tbListarPapeleta;
    private javax.swing.JLabel titulo5;
    public static javax.swing.JTextField txtBuscarr;
    // End of variables declaration//GEN-END:variables
}
